import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';

const $=s=>document.querySelector(s),canvas=$('#scene'),loader=$('#loader'),sections=[...document.querySelectorAll('section')],rail=[...document.querySelectorAll('.route-rail i')],step=$('#step'),place=$('#place'),meta=$('#meta');
const clamp=THREE.MathUtils.clamp,damp=THREE.MathUtils.damp,UP=new THREE.Vector3(0,1,0),FORWARD=new THREE.Vector3(0,0,-1),coarse=matchMedia('(pointer:coarse)').matches,reduceMotion=matchMedia('(prefers-reduced-motion:reduce)').matches;
const portrait=()=>innerWidth/innerHeight<.78;
const C={paper:0xf7f0e1,paper2:0xe9decb,ink:0x23343a,road:0x414c51,road2:0x5c6568,lane:0xf8f0d7,sea:0x2299c2,seaHi:0x59cadd,river:0x3b8fa7,sand:0xe5c484,palm:0x2f7654,palm2:0x579765,wood:0x8e6748,cream:0xf1e6d7,white:0xf7f4ec,coral:0xe06a52,blueGlass:0x247aa0,brick:0xa95032,brick2:0x7e3b29,rock:0xb18a65,rock2:0x765d4d,hill:0x78926c,city:0xd7d7d0,city2:0xbec9c7,sky:0xd4ebef};
const mat=(color,rough=.7,metal=.02,flat=false)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,flatShading:flat});
const pmat=(color,rough=.88)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:0,side:THREE.DoubleSide});

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1.25:1.65));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(C.sky);scene.fog=new THREE.FogExp2(C.sky,.0042);
const camera=new THREE.PerspectiveCamera(portrait()?58:48,innerWidth/innerHeight,.05,560);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.035).texture;pmrem.dispose();
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),coarse?.12:.18,.38,.9);composer.addPass(bloom);composer.addPass(new OutputPass());
const hemi=new THREE.HemisphereLight(0xf9fdff,0x5d6c58,1.95);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffedcf,4.8);sun.position.set(-10,17,8);sun.castShadow=true;sun.shadow.mapSize.set(coarse?768:1024,coarse?768:1024);sun.shadow.camera.left=-26;sun.shadow.camera.right=26;sun.shadow.camera.top=24;sun.shadow.camera.bottom=-24;sun.shadow.camera.near=.5;sun.shadow.camera.far=95;sun.shadow.bias=-.0008;scene.add(sun);scene.add(sun.target);const fill=new THREE.DirectionalLight(0x9ad6e5,1.15);fill.position.set(10,9,-7);scene.add(fill);

const routePts=[
 new THREE.Vector3(0,.42,16),new THREE.Vector3(-1,.44,-8),new THREE.Vector3(1,.46,-34),new THREE.Vector3(-2,.48,-60),
 new THREE.Vector3(-5,.50,-88),new THREE.Vector3(-2,.55,-116),new THREE.Vector3(3,.62,-144),
 new THREE.Vector3(7,.75,-172),new THREE.Vector3(5,1.55,-198),new THREE.Vector3(1,2.55,-221),new THREE.Vector3(-3,2.25,-246),
 new THREE.Vector3(-5,1.2,-273),new THREE.Vector3(-1,.95,-302),new THREE.Vector3(4,1.05,-332),new THREE.Vector3(1,1.2,-362)
];
const curve=new THREE.CatmullRomCurve3(routePts,false,'catmullrom',.56);
function basis(t){t=clamp(t,0,1);const p=curve.getPointAt(t),tangent=curve.getTangentAt(t).normalize();let side=new THREE.Vector3().crossVectors(tangent,UP).normalize();if(side.lengthSq()<.2)side.set(1,0,0);const normal=new THREE.Vector3().crossVectors(side,tangent).normalize();return{p,tangent,side,normal}}
function ribbon(from,to,a,b,material,y=0){const seg=Math.max(24,Math.round((to-from)*700)),pos=[],idx=[];for(let i=0;i<=seg;i++){const t=from+(to-from)*i/seg,{p,side,normal}=basis(t),l=p.clone().addScaledVector(side,a).addScaledVector(normal,y),r=p.clone().addScaledVector(side,b).addScaledVector(normal,y);pos.push(l.x,l.y,l.z,r.x,r.y,r.z);if(i<seg){const k=i*2;idx.push(k,k+1,k+2,k+1,k+3,k+2)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();const m=new THREE.Mesh(g,material);m.receiveShadow=true;scene.add(m);return m}
function fullRibbon(width,material,y=0){return ribbon(0,1,width/2,-width/2,material,y)}
function lineAlong(offset,color,opacity=.8){const pts=[];for(let i=0;i<=600;i++){const {p,side,normal}=basis(i/600);pts.push(p.clone().addScaledVector(side,offset).addScaledVector(normal,.045))}const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity}));scene.add(l);return l}
function placeAt(t,offset,obj,y=0){const {p,tangent,side,normal}=basis(t);obj.position.copy(p).addScaledVector(side,offset).addScaledVector(normal,y);obj.quaternion.setFromUnitVectors(FORWARD,tangent);scene.add(obj);return obj}

fullRibbon(52,pmat(C.paper2),-.31);fullRibbon(50,pmat(C.paper),-.23);fullRibbon(7.6,mat(C.road2,.86),-.015);fullRibbon(6.8,mat(C.road,.78,.015),.01);lineAlong(3.4,C.lane,.82);lineAlong(-3.4,C.lane,.82);
for(let t=.012;t<.995;t+=.019){const {p,tangent,normal}=basis(t),d=new THREE.Mesh(new RoundedBoxGeometry(.08,.018,.76,2,.02),new THREE.MeshBasicMaterial({color:C.lane}));d.position.copy(p).addScaledVector(normal,.055);d.quaternion.setFromUnitVectors(FORWARD,tangent);scene.add(d)}

ribbon(0,.38,-5,-12,pmat(C.sand),-.20);ribbon(0,.38,-12,-48,mat(C.sea,.24,.02,true),-.29);
ribbon(0,.46,5,24,pmat(0xd8d3c7),-.22);
ribbon(.42,.72,-6,-32,mat(C.river,.3,.02,true),-.30);ribbon(.42,.72,6,26,pmat(0x91aa86),-.22);
ribbon(.70,1,-6,-42,mat(C.sea,.24,.02,true),-.29);ribbon(.70,1,6,23,pmat(0x9bb18f),-.22);

function rounded(w,h,d,color,r=.12,rough=.7,metal=.02){const m=new THREE.Mesh(new RoundedBoxGeometry(w,h,d,4,r),mat(color,rough,metal));m.castShadow=true;m.receiveShadow=true;return m}
function shadowBlob(w=4,d=2,opacity=.18){const c=document.createElement('canvas');c.width=256;c.height=128;const q=c.getContext('2d'),g=q.createRadialGradient(128,64,3,128,64,96);g.addColorStop(0,`rgba(25,40,46,${opacity})`);g.addColorStop(1,'rgba(25,40,46,0)');q.fillStyle=g;q.fillRect(0,0,256,128);const tex=new THREE.CanvasTexture(c);const m=new THREE.Mesh(new THREE.PlaneGeometry(w,d),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,toneMapped:false}));m.rotation.x=-Math.PI/2;m.position.y=.015;return m}
function foldLine(w=7,color=0xb9ad96){return new THREE.Mesh(new THREE.BoxGeometry(w,.016,.035),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.55}))}
function treeAt(t,off,s=1){const g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.08*s,.13*s,1.5*s,7),mat(C.wood,.95,0,true));tr.position.y=.75*s;g.add(tr);for(let i=0;i<2;i++){const crown=new THREE.Mesh(new THREE.IcosahedronGeometry((.72-i*.1)*s,1),mat(i?C.palm:C.palm2,.9,0,true));crown.scale.y=.82;crown.position.y=(1.65+i*.42)*s;g.add(crown)}placeAt(t,off,g);return g}
function palmAt(t,off,s=2.5){const g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.065,.115,s,8),mat(C.wood,.95,0,true));tr.position.y=s/2;tr.rotation.z=.035;g.add(tr);for(let k=0;k<8;k++){const leaf=new THREE.Mesh(new THREE.ConeGeometry(.1,1.05,4),mat(k%2?C.palm:C.palm2,.88,0,true));leaf.position.y=s;leaf.rotation.z=Math.PI/2;leaf.rotation.y=k*Math.PI/4;leaf.position.x=Math.cos(k*Math.PI/4)*.34;leaf.position.z=Math.sin(k*Math.PI/4)*.34;g.add(leaf)}placeAt(t,off,g);return g}
function buildingAt(t,off,w,h,d,color){const b=rounded(w,h,d,color,.1,.78,.02);b.position.y=h/2;placeAt(t,off,b);const cap=rounded(w*.88,.08,d*.88,0xf0eee7,.035,.75,0);cap.position.y=h/2+.04;b.add(cap);for(let y=.9;y<h-.5;y+=.85){for(const x of[-w*.22,w*.22]){const win=new THREE.Mesh(new THREE.PlaneGeometry(.18,.3),new THREE.MeshBasicMaterial({color:0x629aae,transparent:true,opacity:.55,toneMapped:false}));win.position.set(x,y-h/2,-d/2-.006);b.add(win)}}return b}

for(let t=.02,i=0;t<.37;t+=.024,i++)palmAt(t,-7.1-(i%2)*.36,2.2+(i%3)*.22);
for(let t=.02,i=0;t<.36;t+=.032,i++){buildingAt(t,7.2+(i%3)*1.25,1.25+(i%2)*.4,4+(i%5)*1.35,1.2,i%3?C.city:C.city2)}
for(let t=.04;t<.36;t+=.04){const {p,side}=basis(t);for(let k=0;k<3;k++){const wave=new THREE.Mesh(new THREE.PlaneGeometry(1.45+.35*k,.045),new THREE.MeshBasicMaterial({color:0xebfbff,transparent:true,opacity:.62,side:THREE.DoubleSide}));wave.rotation.x=-Math.PI/2;wave.position.copy(p).addScaledVector(side,-15-k*5);wave.position.y-=.19;scene.add(wave)}}
for(let i=0;i<8;i++){const t=.02+i*.043,{p,side}=basis(t),m=new THREE.Mesh(new THREE.ConeGeometry(4.5+(i%3),6+(i%4)*1.2,7),pmat(i%2?0x75917e:0x66867a));m.position.copy(p).addScaledVector(side,-34-(i%2)*5);m.position.y+=1.6;m.scale.z=.6;scene.add(m)}

for(let i=0;i<50;i++){const t=.43+Math.random()*.28,s=i%2?1:-1;treeAt(t,s*(8+Math.random()*9),.65+Math.random()*.5)}
for(let i=0;i<24;i++){const t=.46+Math.random()*.22,s=i%2?1:-1;if(s>0)buildingAt(t,9+Math.random()*9,.9+Math.random()*.7,2+Math.random()*4,1+Math.random()*.8,i%2?0xd6d1c6:0xbfcac7)}
function boatAt(t,off,s=.8){const {p,side}=basis(t),g=new THREE.Group(),hull=new THREE.Mesh(new THREE.CylinderGeometry(.18,.28,1.5,6),mat(0x6f4430,.75,0,true));hull.rotation.z=Math.PI/2;hull.scale.y=.55;g.add(hull);const cabin=rounded(.48,.35,.5,0xf1e4ce,.06,.8,0);cabin.position.y=.34;g.add(cabin);g.position.copy(p).addScaledVector(side,off);g.position.y-=.12;g.scale.setScalar(s);scene.add(g)}
for(let i=0;i<10;i++)boatAt(.48+i*.018,-12-(i%4)*3,.55+(i%3)*.12);
for(let t=.48;t<.66;t+=.012){const {p,tangent,side,normal}=basis(t);for(const s of[-1,1]){const railM=rounded(.06,.38,1.9,0xe7e5de,.025,.42,.12);railM.position.copy(p).addScaledVector(side,s*3.72).addScaledVector(normal,.26);railM.quaternion.setFromUnitVectors(FORWARD,tangent);scene.add(railM)}}
for(let t=.50;t<.66;t+=.035){const {p,side}=basis(t);for(const s of[-1,1]){const py=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,2.6,8),mat(0xb8b9b4,.78,.02,true));py.position.copy(p).addScaledVector(side,s*2.7);py.position.y-=1.25;scene.add(py)}}

for(let i=0;i<46;i++){const t=.72+Math.random()*.26,s=i%2?1:-1;if(s>0)treeAt(t,8+Math.random()*9,.6+Math.random()*.45);else if(i<24)palmAt(t,-7-Math.random()*3,1.8+Math.random()*.5)}
for(let i=0;i<18;i++){const t=.73+Math.random()*.24;buildingAt(t,9+Math.random()*10,.8+Math.random()*.8,2.8+Math.random()*5,1+Math.random()*.9,i%2?0xd9d6cc:0xc2d0d0)}

function makeCar(){const g=new THREE.Group(),body=mat(0xe6e2d9,.34,.2),body2=mat(0x9da9a9,.42,.35),dark=mat(0x172126,.28,.58),glass=mat(0x3e7185,.18,.35),chrome=mat(0xcbd5d4,.2,.78),light=new THREE.MeshStandardMaterial({color:0xf7ffff,emissive:0xbff5ff,emissiveIntensity:3.2});
 const lower=new THREE.Mesh(new RoundedBoxGeometry(1.98,.42,3.5,5,.17),body);lower.position.y=.5;g.add(lower);const belt=new THREE.Mesh(new RoundedBoxGeometry(1.9,.16,2.8,4,.08),body2);belt.position.set(0,.67,.05);g.add(belt);const hood=new THREE.Mesh(new RoundedBoxGeometry(1.72,.23,1.25,4,.12),body);hood.position.set(0,.78,-1.2);hood.rotation.x=-.055;g.add(hood);const cabin=new THREE.Mesh(new RoundedBoxGeometry(1.3,.66,1.42,5,.2),glass);cabin.position.set(0,1.01,.08);g.add(cabin);const roof=new THREE.Mesh(new RoundedBoxGeometry(1.05,.075,.86,3,.07),dark);roof.position.set(0,1.35,.08);g.add(roof);const splitter=rounded(1.72,.07,.22,0xd86d50,.035,.38,.1);splitter.position.set(0,.31,-1.77);g.add(splitter);
 g.userData.wheels=[];for(const [x,z] of [[-.92,-1.05],[.92,-1.05],[-.92,1.08],[.92,1.08]]){const tire=new THREE.Mesh(new THREE.CylinderGeometry(.33,.33,.24,18),dark);tire.rotation.z=Math.PI/2;tire.position.set(x,.35,z);g.add(tire);const rim=new THREE.Mesh(new THREE.CylinderGeometry(.17,.17,.25,12),chrome);rim.rotation.z=Math.PI/2;rim.position.copy(tire.position);g.add(rim);g.userData.wheels.push(tire,rim)}
 for(const x of[-.56,.56]){const l=new THREE.Mesh(new RoundedBoxGeometry(.35,.075,.04,2,.02),light);l.position.set(x,.7,-1.77);g.add(l)}const tailMat=new THREE.MeshStandardMaterial({color:0xff6f61,emissive:0xff392c,emissiveIntensity:2.5});for(const x of[-.58,.58]){const l=new THREE.Mesh(new RoundedBoxGeometry(.38,.065,.035,2,.02),tailMat);l.position.set(x,.66,1.76);g.add(l)}g.add(shadowBlob(3.2,1.5,.3));return g}
const car=makeCar();scene.add(car);

const popups=[];
function smoothstep(a,b,x){x=clamp((x-a)/(b-a),0,1);return x*x*(3-2*x)}
function overshoot(x){x=clamp(x,0,1);return 1-(1-x)*(1-x)*(1+1.35*(1-x));}
function popupAt(t,off,name,builder,opts={}){const {p,tangent,side}=basis(t),anchor=new THREE.Group();anchor.position.copy(p).addScaledVector(side,off);anchor.quaternion.setFromUnitVectors(FORWARD,tangent);
 const page=new THREE.Group();anchor.add(page);const base=new THREE.Mesh(new RoundedBoxGeometry(opts.w||8,.10,opts.d||5,3,.1),pmat(opts.paper||C.cream));base.position.y=.04;base.receiveShadow=true;page.add(base);const fold=foldLine((opts.w||8)*.78);fold.position.set(0,.105,-(opts.d||5)*.31);page.add(fold);
 const back=new THREE.Group();back.position.z=.35;back.rotation.x=-Math.PI/2;page.add(back);const hero=new THREE.Group();hero.position.z=-.22;hero.rotation.x=-Math.PI/2;page.add(hero);builder({page,back,hero,base});const label=makeLabel(name,opts.accent||C.coral);label.position.set(0,opts.labelY||4.8,.1);hero.add(label);anchor.add(shadowBlob((opts.w||8)*1.05,(opts.d||5)*.8,.16));scene.add(anchor);popups.push({t,page,back,hero});return anchor}
function makeLabel(text,accent){const c=document.createElement('canvas');c.width=720;c.height=150;const q=c.getContext('2d');q.fillStyle='#fbf6ec';q.beginPath();q.roundRect(8,8,704,134,26);q.fill();q.fillStyle='#23343a';q.font='700 42px -apple-system,system-ui';q.textAlign='center';q.textBaseline='middle';q.fillText(text,360,73);q.fillStyle=`#${accent.toString(16).padStart(6,'0')}`;q.fillRect(322,118,76,5);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return new THREE.Mesh(new THREE.PlaneGeometry(3.7,.77),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide,toneMapped:false}))}
function updatePopup(pp){const d=progress-pp.t;const enter=smoothstep(-.12,-.03,d),leave=1-smoothstep(.075,.145,d),open=clamp(Math.min(enter,leave),0,1);const b=overshoot(smoothstep(0,.72,open)),h=overshoot(smoothstep(.16,1,open));pp.page.position.y=Math.sin(open*Math.PI)*.015;pp.back.rotation.x=-Math.PI/2+Math.PI/2*b;pp.hero.rotation.x=-Math.PI/2+Math.PI/2*h;pp.hero.position.y=Math.sin(h*Math.PI)*.07}

function tramHuong({back,hero}){const skyline=new THREE.Group();for(let i=0;i<7;i++){const b=rounded(.65+(i%2)*.22,1.3+(i%4)*.55,.55,i%2?C.city:C.city2,.06,.8,0);b.position.set(-3+i, .65+(i%4)*.275,1.3+(i%2)*.2);skyline.add(b)}back.add(skyline);
 const base=new THREE.Mesh(new THREE.CylinderGeometry(1.45,1.68,.42,10),pmat(0xe4d7c4));base.position.y=.22;hero.add(base);const core=new THREE.Mesh(new THREE.CylinderGeometry(.57,.75,3.6,10),mat(C.blueGlass,.25,.22));core.position.y=2.02;hero.add(core);
 const petalShape=new THREE.Shape();petalShape.moveTo(-.34,0);petalShape.bezierCurveTo(-.72,.8,-.62,2.0,0,3.35);petalShape.bezierCurveTo(.62,2.0,.72,.8,.34,0);petalShape.closePath();const pg=new THREE.ExtrudeGeometry(petalShape,{depth:.12,bevelEnabled:true,bevelSize:.035,bevelThickness:.03,bevelSegments:2});
 for(let i=0;i<6;i++){const p=new THREE.Mesh(pg,pmat(i%2?0xf3e7d5:0xf7f1e7));const a=i*Math.PI/3;p.position.set(Math.cos(a)*.78,.48,Math.sin(a)*.78);p.rotation.y=-a;p.castShadow=true;hero.add(p)}
 const tip=new THREE.Mesh(new THREE.ConeGeometry(.26,.9,8),pmat(0xf4eadb));tip.position.y=4.55;hero.add(tip);hero.add(shadowBlob(4.6,2.4,.17));
}

function xomBong({back,hero}){const water=new THREE.Mesh(new THREE.PlaneGeometry(8.5,4.2,12,8),mat(C.river,.25,.02,true));water.rotation.x=-Math.PI/2;water.position.y=.02;hero.add(water);const bridge=new THREE.Group(),deck=rounded(7.7,.22,1.25,0xbfc4c1,.06,.65,.03);deck.position.y=1.25;bridge.add(deck);for(const s of[-1,1]){const rail=rounded(7.7,.16,.07,0xebeae3,.03,.45,.12);rail.position.set(0,1.48,s*.59);bridge.add(rail)}for(const x of[-2.6,0,2.6]){const py=new THREE.Mesh(new THREE.CylinderGeometry(.13,.18,1.2,8),mat(0xa9adaa,.78,.01,true));py.position.set(x,.62,0);bridge.add(py)}bridge.rotation.y=Math.PI/2;hero.add(bridge);
 for(let i=0;i<4;i++){const boat=new THREE.Mesh(new THREE.CylinderGeometry(.12,.23,1.05,6),mat(i%2?0x7f513b:0xc65e45,.75,0,true));boat.rotation.z=Math.PI/2;boat.scale.y=.5;boat.position.set(-2.6+i*1.7,.13,-1.2+(i%2)*2.3);hero.add(boat)}
 const city=new THREE.Group();for(let i=0;i<8;i++){const b=rounded(.55+(i%3)*.18,1.0+(i%4)*.45,.55,i%2?0xc6cfcb:0xe2ddd2,.05,.8,0);b.position.set(-3.4+i*.95,.5+(i%4)*.22,1.7);city.add(b)}back.add(city);
}

function poNagar({back,hero}){const hill=new THREE.Mesh(new THREE.CylinderGeometry(4.2,4.9,.75,12),pmat(C.hill));hill.scale.z=.72;hill.position.y=.37;hero.add(hill);const terrace=rounded(6.0,.34,3.7,0x9a7555,.05,.9,0);terrace.position.y=.92;hero.add(terrace);
 function tower(x,z,s=1){const g=new THREE.Group(),brick=pmat(C.brick),dark=pmat(C.brick2);const body=rounded(1.3*s,2.75*s,1.28*s,C.brick,.04,.95,0);body.position.y=1.37*s;g.add(body);const shoulder=new THREE.Mesh(new THREE.CylinderGeometry(.9*s,.76*s,.52*s,4),brick);shoulder.rotation.y=Math.PI/4;shoulder.position.y=3.0*s;g.add(shoulder);const spire=new THREE.Mesh(new THREE.ConeGeometry(.7*s,1.55*s,4),dark);spire.rotation.y=Math.PI/4;spire.position.y=3.92*s;g.add(spire);const top=new THREE.Mesh(new THREE.ConeGeometry(.28*s,.72*s,4),brick);top.rotation.y=Math.PI/4;top.position.y=4.83*s;g.add(top);const door=new THREE.Mesh(new THREE.PlaneGeometry(.42*s,.9*s),new THREE.MeshBasicMaterial({color:0x3a241f,side:THREE.DoubleSide}));door.position.set(0,.72*s,-.647*s);g.add(door);g.position.set(x,1.08,z);g.scale.setScalar(s);hero.add(g)}
 tower(0,.1,1.08);tower(-2.0,.25,.76);tower(1.95,.55,.7);tower(-.9,1.6,.55);const trees=new THREE.Group();for(let i=0;i<12;i++){const c=new THREE.Mesh(new THREE.IcosahedronGeometry(.38+(i%3)*.08,1),mat(i%2?C.palm:C.palm2,.9,0,true));c.position.set(-3.4+(i%6)*1.3,1.0+(i%2)*.15,-1.3+Math.floor(i/6)*3);trees.add(c)}hero.add(trees);const riverBand=new THREE.Mesh(new THREE.PlaneGeometry(8,1.6),new THREE.MeshBasicMaterial({color:C.river,transparent:true,opacity:.6,side:THREE.DoubleSide}));riverBand.position.set(0,1.7,2.0);back.add(riverBand);
}

function honChong({back,hero}){const water=new THREE.Mesh(new THREE.PlaneGeometry(8.8,4.8,12,8),mat(C.sea,.25,.02,true));water.rotation.x=-Math.PI/2;water.position.y=.01;hero.add(water);const cape=rounded(7.8,.13,2.45,C.sand,.08,.9,0);cape.position.set(0,.08,-.8);hero.add(cape);const rockMat=mat(C.rock,.9,0,true),rockDark=mat(C.rock2,.92,0,true);const positions=[[-2.7,.55,-.7,1.0],[-1.7,.72,-.65,1.18],[-.55,.62,-.9,.95],[.55,.82,-.75,1.25],[1.7,.58,-.6,.92],[2.8,.48,-.65,.8],[-1.0,1.35,-.55,.88],[.45,1.52,-.55,1.0]];for(let i=0;i<positions.length;i++){const [x,y,z,s]=positions[i],r=new THREE.Mesh(new THREE.DodecahedronGeometry(.78*s,0),i%2?rockMat:rockDark);r.scale.set(1.35,.82,1);r.position.set(x,y,z);r.rotation.set(i*.2,i*.33,i*.12);r.castShadow=true;hero.add(r)}
 const big=new THREE.Mesh(new THREE.DodecahedronGeometry(1.0,0),rockMat);big.scale.set(1.35,.92,1.02);big.position.set(.35,2.65,-.48);big.rotation.set(.1,.33,.12);big.castShadow=true;hero.add(big);
 const mountains=new THREE.Group();for(let i=0;i<5;i++){const m=new THREE.Mesh(new THREE.ConeGeometry(1.4+(i%2)*.4,2.1+(i%3)*.5,7),pmat(i%2?0x668679:0x779486));m.position.set(-3.7+i*1.85,1.05,1.8);m.scale.z=.55;mountains.add(m)}back.add(mountains);
}

popupAt(.24,-9.7,'THÁP TRẦM HƯƠNG',tramHuong,{w:9,d:5.5,labelY:5.45,accent:C.blueGlass,paper:0xf1e4d4});
popupAt(.50,-9.9,'CẦU XÓM BÓNG',xomBong,{w:9.5,d:5.7,labelY:4.0,accent:C.river,paper:0xe9e1d2});
popupAt(.66,10.2,'THÁP BÀ PO NAGAR',poNagar,{w:9.5,d:6.2,labelY:6.4,accent:C.brick,paper:0xead8c8});
popupAt(.88,-10.0,'HÒN CHỒNG',honChong,{w:9.7,d:6.2,labelY:4.75,accent:C.sea,paper:0xeee1c9});

let target=.004,progress=.004,velocity=0,lastY=scrollY,first=true;const carQ=new THREE.Quaternion(),camQ=new THREE.Quaternion(),camPos=new THREE.Vector3(),lookM=new THREE.Matrix4(),clock=new THREE.Clock();
function onScroll(){const total=Math.max(document.documentElement.scrollHeight-innerHeight,1);target=.004+(scrollY/total)*.992;velocity=Math.min(1,velocity+Math.abs(scrollY-lastY)/650);lastY=scrollY}addEventListener('scroll',onScroll,{passive:true});onScroll();
function syncHud(){const total=Math.max(document.documentElement.scrollHeight-innerHeight,1),p=scrollY/total,idx=clamp(Math.floor(p*sections.length),0,sections.length-1),s=sections[idx];step.textContent=String(idx+1).padStart(2,'0');place.textContent=s.dataset.place;meta.textContent=s.dataset.meta;rail.forEach((r,i)=>r.classList.toggle('active',i===idx));document.documentElement.style.setProperty('--progress',(p*100)+'%')}
function render(){requestAnimationFrame(render);const dt=Math.min(clock.getDelta(),.04);progress=damp(progress,target,reduceMotion?14:3.25,dt);velocity=damp(velocity,0,3.0,dt);syncHud();const {p,tangent,side,normal}=basis(progress);car.position.copy(p).addScaledVector(normal,.035);carQ.setFromUnitVectors(FORWARD,tangent);car.quaternion.slerp(carQ,1-Math.exp(-dt*9));for(const w of car.userData.wheels)w.rotation.x-=dt*(7+velocity*22);popups.forEach(updatePopup);
 const back=portrait()?11.6:10.0,height=portrait()?5.1:4.2,sideOffset=portrait()?.2:1.0;const desired=p.clone().addScaledVector(tangent,-back).addScaledVector(normal,height).addScaledVector(side,sideOffset);if(first)camPos.copy(desired);else camPos.lerp(desired,1-Math.exp(-dt*3.45));camera.position.copy(camPos);const focus=curve.getPointAt(clamp(progress+(portrait()?.058:.07),0,1)).addScaledVector(UP,.55);lookM.lookAt(camera.position,focus,UP);camQ.setFromRotationMatrix(lookM);camera.quaternion.slerp(camQ,first?1:1-Math.exp(-dt*4.1));first=false;const baseFov=portrait()?59:48;camera.fov=damp(camera.fov,baseFov+velocity*1.6,3,dt);camera.updateProjectionMatrix();sun.target.position.copy(p);sun.target.updateMatrixWorld();bloom.strength=damp(bloom.strength,(coarse?.11:.17)+velocity*.03,2.5,dt);composer.render()}
render();setTimeout(()=>loader.classList.add('done'),650);
addEventListener('resize',()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1.25:1.65));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=portrait()?59:48;camera.updateProjectionMatrix();composer.setSize(innerWidth,innerHeight)});
