(()=>{
 const root=document.documentElement,stage=document.getElementById('stage'),hold=document.getElementById('hold'),scan=document.getElementById('scan'),pct=document.getElementById('pct'),phase=document.getElementById('phase'),kicker=document.getElementById('kicker'),title=document.getElementById('title'),subtitle=document.getElementById('subtitle'),dots=[...document.querySelectorAll('.chapter i')],dust=document.getElementById('dust'),ctx=dust.getContext('2d'),pulse=document.getElementById('pulse'),explore=document.getElementById('explore');
 const coarse=matchMedia('(pointer:coarse)').matches,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let tx=0,ty=0,mx=0,my=0,targetP=0,p=0,charge=0,charging=false,releaseEnergy=0,last=performance.now(),W=innerWidth,H=innerHeight,dpr=1,parts=[];
 const chapters=[
  {phase:'ARRIVAL / 01',k:'SYSTEM / DORMANT',t:'<span>THE RELIC</span><em>AWAKENS.</em>',s:'An adaptive biomechanical object suspended between artifact and organism. Scroll to approach. Hold the field to wake it.'},
  {phase:'PROXIMITY / 02',k:'FIELD / REACTIVE',t:'<span>IT NOTICES</span><em>MOVEMENT.</em>',s:'Camera, particles and the relic no longer move as separate layers. Your position bends the entire field.'},
  {phase:'DISSECTION / 03',k:'CORE / EXPOSED',t:'<span>OPEN THE</span><em>INNER SHELL.</em>',s:'The deeper state reveals the core. Hold to charge; release to force the structure into a brief defensive pulse.'},
  {phase:'CONVERGENCE / 04',k:'SIGNAL / ACTIVE',t:'<span>THE FIELD</span><em>REMEMBERS.</em>',s:'At maximum proximity, motion compresses into the core and the foreground crosses the lens before the system settles.'}
 ];
 function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,coarse?1.45:1.9);dust.width=Math.round(W*dpr);dust.height=Math.round(H*dpr);dust.style.width=W+'px';dust.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);parts=Array.from({length:coarse?92:160},(_,i)=>({x:Math.random()*W,y:Math.random()*H,z:Math.random(),v:.15+Math.random()*.55,r:.35+Math.random()*1.5,a:.08+Math.random()*.45}))}
 function pointer(x,y){tx=(x/W-.5)*2;ty=(y/H-.5)*2}
 addEventListener('pointermove',e=>pointer(e.clientX,e.clientY),{passive:true});
 addEventListener('touchmove',e=>{const t=e.touches[0];if(t)pointer(t.clientX,t.clientY)},{passive:true});
 addEventListener('scroll',()=>{const max=Math.max(1,document.documentElement.scrollHeight-H);targetP=Math.max(0,Math.min(1,scrollY/max))},{passive:true});
 addEventListener('resize',resize,{passive:true});resize();
 let chapter=-1;function setChapter(i){if(i===chapter)return;chapter=i;const c=chapters[i];phase.textContent=c.phase;kicker.textContent=c.k;title.innerHTML=c.t;subtitle.textContent=c.s;dots.forEach((d,n)=>d.classList.toggle('on',n===i));document.querySelector('.copy').animate([{opacity:.55,transform:innerWidth<820?'translateY(7px)':'translateY(calc(-44% + 9px))'},{opacity:1,transform:innerWidth<820?'none':'translateY(-44%)'}],{duration:420,easing:'cubic-bezier(.2,.8,.2,1)'})}
 function beginCharge(e){e?.preventDefault();charging=true;hold.setPointerCapture?.(e.pointerId)}
 function release(){if(!charging&&charge<.08)return;charging=false;releaseEnergy=Math.max(.45,charge);charge=0;stage.classList.remove('releasing');void stage.offsetWidth;stage.classList.add('releasing');setTimeout(()=>stage.classList.remove('releasing'),950);burst();navigator.vibrate?.([12,16,24])}
 hold.addEventListener('pointerdown',beginCharge);hold.addEventListener('pointerup',release);hold.addEventListener('pointercancel',release);hold.addEventListener('lostpointercapture',()=>{if(charging)release()});
 pulse.addEventListener('click',()=>{charge=.92;release()});explore.addEventListener('click',()=>scrollTo({top:document.documentElement.scrollHeight*.28,behavior:'smooth'}));
 document.getElementById('sound').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent.includes('Off')?'Sound: On':'Sound: Off'});
 function burst(){const cx=W*(innerWidth<820?.555:.649),cy=H*(innerWidth<820?.415:.496);for(let i=0;i<(coarse?36:58);i++){const a=Math.random()*Math.PI*2,s=55+Math.random()*220;parts.push({x:cx,y:cy,z:1,v:0,r:1+Math.random()*2.8,a:.8,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.75+Math.random()*.55})}}
 function draw(dt){ctx.clearRect(0,0,W,H);ctx.save();ctx.globalCompositeOperation='screen';for(let i=parts.length-1;i>=0;i--){const q=parts[i];if(q.life!==undefined){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.985;q.vy*=.985;if(q.life<=0){parts.splice(i,1);continue}const a=Math.max(0,q.life)*.72;ctx.fillStyle=`rgba(190,255,208,${a})`;ctx.shadowBlur=12;ctx.shadowColor='rgba(130,255,170,.55)';ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,Math.PI*2);ctx.fill();continue}q.y-=q.v*(.45+p*1.25);q.x+=mx*q.z*.11;if(q.y<-8){q.y=H+8;q.x=Math.random()*W}if(q.x<-10)q.x=W+8;if(q.x>W+10)q.x=-8;const a=q.a*(.55+q.z*.65)*(1+p*.22);ctx.fillStyle=`rgba(205,244,216,${a})`;ctx.shadowBlur=q.z>0.75?8:0;ctx.shadowColor='rgba(156,255,183,.35)';ctx.beginPath();ctx.arc(q.x,q.y,q.r*(.65+q.z*1.2),0,Math.PI*2);ctx.fill()}ctx.restore()}
 function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;mx+=(tx-mx)*.055;my+=(ty-my)*.055;p+=(targetP-p)*.065;if(charging)charge=Math.min(1,charge+dt*1.05);else charge*=.91;releaseEnergy*=.91;root.style.setProperty('--mx',mx.toFixed(3));root.style.setProperty('--my',my.toFixed(3));root.style.setProperty('--p',p.toFixed(4));root.style.setProperty('--charge',Math.min(1,charge+releaseEnergy*.35).toFixed(3));const scanP=18+((p*.74 + (Math.sin(now*.00035)*.5+.5)*.08)%1)*68;root.style.setProperty('--scan',scanP.toFixed(1)+'%');pct.textContent=String(Math.round(p*100)).padStart(2,'0')+'%';const i=Math.min(3,Math.floor(p*4));setChapter(i);draw(dt);requestAnimationFrame(loop)}
 if(reduce){targetP=p=0;root.style.setProperty('--scan','48%')}
 requestAnimationFrame(loop);
})();