import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const canvas=document.querySelector('#scene'),rail=document.querySelector('.rail i'),stageEl=document.querySelector('#stageNow');
const mobile=()=>innerWidth<760,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,smooth=t=>t*t*(3-2*t);

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile()?1.35:1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x080c13,.025);
const camera=new THREE.PerspectiveCamera(mobile()?39:34,innerWidth/innerHeight,.1,100);camera.position.set(0,7.5,mobile()?23:25);
const root=new THREE.Group(),castle=new THREE.Group(),atmo=new THREE.Group();scene.add(root);root.add(castle,atmo);

function texture(kind){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');
 if(kind==='stone'){x.fillStyle='#9ca2a4';x.fillRect(0,0,256,256);for(let y=0;y<256;y+=24){const off=(y/24)%2?18:0;for(let i=-1;i<9;i++){const xx=i*36+off;x.fillStyle=`rgb(${138+Math.random()*18|0},${143+Math.random()*16|0},${143+Math.random()*15|0})`;x.fillRect(xx+1,y+1,34,21);x.strokeStyle='rgba(35,40,43,.25)';x.strokeRect(xx+.5,y+.5,35,22)}}for(let i=0;i<900;i++){x.fillStyle=`rgba(20,25,28,${Math.random()*.08})`;x.fillRect(Math.random()*256,Math.random()*256,1,1)}}
 else{x.fillStyle='#283746';x.fillRect(0,0,256,256);x.strokeStyle='rgba(115,145,164,.22)';x.lineWidth=2;for(let y=-30;y<280;y+=18){for(let xx=-40;xx<280;xx+=26){x.beginPath();x.moveTo(xx,y);x.lineTo(xx+18,y+15);x.stroke()}}}
 const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
const stoneTex=texture('stone'),roofTex=texture('roof');
const stone=new THREE.MeshStandardMaterial({map:stoneTex,color:0x8e9699,roughness:.96,metalness:.01}),stoneDark=new THREE.MeshStandardMaterial({map:stoneTex,color:0x5c6469,roughness:.98}),roofMat=new THREE.MeshStandardMaterial({map:roofTex,color:0x273747,roughness:.8,metalness:.08}),metal=new THREE.MeshStandardMaterial({color:0xb49a68,roughness:.32,metalness:.58}),wood=new THREE.MeshStandardMaterial({color:0x4b3327,roughness:.9}),black=new THREE.MeshStandardMaterial({color:0x0f141a,roughness:1}),glow=new THREE.MeshStandardMaterial({color:0xffc86f,emissive:0xff9d38,emissiveIntensity:3,roughness:.45}),grass=new THREE.MeshStandardMaterial({color:0x32423a,roughness:1}),rockMat=new THREE.MeshStandardMaterial({color:0x343a40,roughness:1}),water=new THREE.MeshPhysicalMaterial({color:0x152936,roughness:.22,metalness:.15,transparent:true,opacity:.86,clearcoat:.7,clearcoatRoughness:.25});

const box=(w,h,d,m=stone)=>{const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.castShadow=q.receiveShadow=true;return q},cyl=(r1,r2,h,s,m=stone)=>{const q=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,s),m);q.castShadow=q.receiveShadow=true;return q},cone=(r,h,s,m=roofMat)=>{const q=new THREE.Mesh(new THREE.ConeGeometry(r,h,s),m);q.castShadow=q.receiveShadow=true;return q};
const modules=[];function module(obj,off,start=.05,end=.85,rot=0){obj.userData.base=obj.position.clone();obj.userData.off=off;obj.userData.start=start;obj.userData.end=end;obj.userData.baseRY=obj.rotation.y;obj.userData.rot=rot;modules.push(obj);castle.add(obj);return obj}
function windowPane(w=.24,h=.7){const g=new THREE.Group(),dark=box(w+.11,h+.12,.05,black),lit=box(w,h,.08,glow);lit.position.z=.045;g.add(dark,lit);return g}
function pointedRoof(r,h,s=8){const g=new THREE.Group(),r1=cone(r,h,s,roofMat),cap=cyl(.055,.055,.75,8,metal),tip=cone(.13,.32,8,metal);cap.position.y=h/2+.28;tip.position.y=h/2+.78;g.add(r1,cap,tip);return g}
function battlement(w,d,y,count=8){const g=new THREE.Group(),gap=w/count;for(let i=0;i<count;i++){const b=box(gap*.58,.35,d,stoneDark);b.position.set(-w/2+gap*(i+.5),y,0);g.add(b)}return g}
function gothicTower(r=1,h=6,roofH=2.5,win=true){const g=new THREE.Group(),base=cyl(r*1.08,r*1.18,.65,12,stoneDark),body=cyl(r,r*1.05,h,12,stone),crown=cyl(r*1.12,r*1.12,.32,12,stoneDark);base.position.y=.33;body.position.y=h/2+.65;crown.position.y=h+.82;g.add(base,body,crown);for(let i=0;i<8;i++){const a=i/8*Math.PI*2,b=box(.28,.42,.48,stoneDark);b.position.set(Math.cos(a)*r*1.08,h+1.05,Math.sin(a)*r*1.08);b.rotation.y=-a;g.add(b)}const rf=pointedRoof(r*1.28,roofH,12);rf.position.y=h+1.05+roofH/2;g.add(rf);if(win)for(let y=2;y<h-.5;y+=1.55)for(let i=0;i<4;i++){const a=i*Math.PI/2+Math.PI/4,p=windowPane(.18,.55);p.position.set(Math.cos(a)*(r+.02),y,Math.sin(a)*(r+.02));p.rotation.y=-a+Math.PI/2;g.add(p)}return g}
function wall(w,h,d=1){const g=new THREE.Group(),body=box(w,h,d,stone);body.position.y=h/2;g.add(body,battlement(w,d+.08,h+.2,Math.max(5,Math.round(w/.75))));for(let x=-w/2+1;x<w/2-.5;x+=1.55){const p=windowPane(.12,.45);p.position.set(x,h*.55,d/2+.05);g.add(p)}return g}
function buttress(h=3.6){const b=box(.48,h,.7,stoneDark);b.rotation.z=-.05;b.position.y=h/2;return b}
function gatehouse(){const g=new THREE.Group(),body=box(4.7,4.2,2.7,stone);body.position.y=2.1;g.add(body,battlement(4.7,2.8,4.38,8));const portal=box(1.65,2.7,.13,black);portal.position.set(0,1.36,1.42);g.add(portal);for(let i=0;i<7;i++){const p=box(.06,2.35,.07,metal);p.position.set(-.54+i*.18,1.28,1.5);g.add(p)}for(const x of[-1.55,1.55]){const t=gothicTower(.62,4.7,1.8,false);t.position.set(x,0,.05);g.add(t)}for(const x of[-.85,.85]){const p=windowPane(.2,.7);p.position.set(x,3,1.4);g.add(p)}return g}
function keepLower(){const g=new THREE.Group(),base=box(7.2,.72,6.4,stoneDark),body=box(5.9,3.1,5.1,stone);base.position.y=.36;body.position.y=2.22;g.add(base,body);for(const x of[-2.45,2.45])for(const z of[-2.05,2.05]){const b=buttress(3.4);b.position.set(x,1.7,z);g.add(b)}for(const z of[-2.6,2.6])for(const x of[-1.45,0,1.45]){const p=windowPane(.24,.8);p.position.set(x,2.25,z+(z>0?.03:-.03));p.rotation.y=z<0?Math.PI:0;g.add(p)}return g}
function keepUpper(){const g=new THREE.Group(),mid=box(4.55,2.6,4.05,stone),neck=box(3.15,2.2,2.75,stone),ledge=box(4.85,.28,4.35,stoneDark);mid.position.y=1.3;ledge.position.y=2.74;neck.position.y=3.95;g.add(mid,ledge,neck);for(let i=0;i<3;i++){const p=windowPane(.22,.78);p.position.set(-1.3+i*1.3,1.25,2.06);g.add(p)}for(const x of[-.85,.85]){const p=windowPane(.18,.65);p.position.set(x,4,1.4);g.add(p)}for(const x of[-1.8,1.8])for(const z of[-1.55,1.55]){const t=gothicTower(.38,2.15,1.2,false);t.position.set(x,2.58,z);g.add(t)}return g}
function crown(){const g=new THREE.Group(),roof=new THREE.Mesh(new THREE.ConeGeometry(2.65,3.25,4),roofMat);roof.rotation.y=Math.PI/4;roof.scale.z=.82;roof.castShadow=true;roof.position.y=1.62;g.add(roof);const spire=cyl(.09,.09,2.3,8,metal);spire.position.y=4.15;g.add(spire);const finial=cone(.18,.5,8,metal);finial.position.y=5.55;g.add(finial);const flag=box(1.15,.34,.035,new THREE.MeshStandardMaterial({color:0x6d1522,roughness:.7}));flag.position.set(.62,5.05,0);g.add(flag);return g}
function bridge(){const g=new THREE.Group(),deck=box(2.1,.22,5.8,wood);deck.position.y=.55;g.add(deck);for(const x of[-1.04,1.04]){const rail=box(.1,.64,5.8,metal);rail.position.set(x,.96,0);g.add(rail)}for(let z=-2.5;z<2.6;z+=.72){const p=box(2,.05,.52,wood);p.position.set(0,.7,z);g.add(p)}return g}

const cliff=new THREE.Group();const island=cyl(9.1,10.8,2.9,18,rockMat);island.position.y=-1.4;cliff.add(island);const lawn=cyl(7.8,8.6,.55,18,grass);lawn.position.y=.12;cliff.add(lawn);for(let i=0;i<34;i++){const a=Math.random()*Math.PI*2,r=7+Math.random()*2.5,s=.4+Math.random()*.9,rr=new THREE.Mesh(new THREE.DodecahedronGeometry(s,0),rockMat);rr.position.set(Math.cos(a)*r,-.1+Math.random()*.8,Math.sin(a)*r);rr.scale.y=.7+Math.random()*1.2;rr.rotation.set(Math.random()*2,Math.random()*2,Math.random()*2);rr.castShadow=true;cliff.add(rr)}const moat=new THREE.Mesh(new THREE.TorusGeometry(8.25,.72,18,72),water);moat.rotation.x=Math.PI/2;moat.position.y=.08;cliff.add(moat);module(cliff,new THREE.Vector3(0,-3.2,0),.03,.38,0);

const br=bridge();br.position.set(0,.1,8.9);module(br,new THREE.Vector3(0,1.2,5.8),.12,.48,0);
const gate=gatehouse();gate.position.set(0,.28,6.3);module(gate,new THREE.Vector3(0,1.4,4.8),.18,.55,.05);
const walls=[];[['f',0,0,5.45],['b',Math.PI,0,-5.45],['l',Math.PI/2,-5.45,0],['r',Math.PI/2,5.45,0]].forEach(([,ry,x,z],i)=>{const w=wall(9.4,2.85,1);w.rotation.y=ry;w.position.set(x,.25,z);walls.push(module(w,new THREE.Vector3(x?Math.sign(x)*4.5:0,1,z?Math.sign(z)*4.5:0),.2,.58,ry*.06))});
[[-5.35,-5.35,6.4],[5.35,-5.35,5.8],[-5.35,5.35,5.5],[5.35,5.35,6.8]].forEach(([x,z,h],i)=>{const t=gothicTower(1.02,h,2.5+i*.14,true);t.position.set(x,.15,z);module(t,new THREE.Vector3(Math.sign(x)*4.5,1.8+i*.2,Math.sign(z)*4.5),.28,.68,Math.sign(x)*.13)});
for(const [x,z,h] of [[-3.2,0,4.2],[3.2,0,4.8],[0,-3.2,4.5]]){const t=gothicTower(.62,h,1.75,true);t.position.set(x,.55,z);module(t,new THREE.Vector3(x*.85,2.2,z*.85),.34,.72,.12)}
const lower=keepLower();lower.position.set(0,.6,0);module(lower,new THREE.Vector3(0,3.3,0),.4,.78,.08);
const upper=keepUpper();upper.position.set(0,4.05,0);module(upper,new THREE.Vector3(0,5,0),.47,.84,-.12);
const top=crown();top.position.set(0,9.55,0);module(top,new THREE.Vector3(0,7.1,0),.55,.9,.18);

for(const a of[0,Math.PI/2,Math.PI,Math.PI*1.5]){const pts=[new THREE.Vector3(Math.cos(a)*2.2,5.1,Math.sin(a)*2.2),new THREE.Vector3(Math.cos(a)*3.1,4.2,Math.sin(a)*3.1),new THREE.Vector3(Math.cos(a)*3.8,3.2,Math.sin(a)*3.8)],curve=new THREE.CatmullRomCurve3(pts),tube=new THREE.Mesh(new THREE.TubeGeometry(curve,10,.12,6,false),stoneDark);tube.castShadow=true;module(tube,new THREE.Vector3(Math.cos(a)*1.6,2.5,Math.sin(a)*1.6),.5,.88,.08)}

const moon=new THREE.Mesh(new THREE.SphereGeometry(1.45,24,24),new THREE.MeshBasicMaterial({color:0xcdd9e5}));moon.position.set(-11,12,-19);atmo.add(moon);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:(()=>{const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(210,226,255,.34)');g.addColorStop(.25,'rgba(160,195,235,.14)');g.addColorStop(1,'rgba(100,150,220,0)');x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c)})(),transparent:true,depthWrite:false}));halo.scale.set(7,7,1);halo.position.copy(moon.position);halo.position.z+=.4;atmo.add(halo);
for(let i=0;i<90;i++){const s=new THREE.Mesh(new THREE.SphereGeometry(.018+Math.random()*.026,5,5),new THREE.MeshBasicMaterial({color:i%4?0xb7c9db:0xffffff}));s.position.set((Math.random()-.5)*40,4+Math.random()*18,-12-Math.random()*18);s.userData.phase=Math.random()*6;atmo.add(s)}

scene.add(new THREE.HemisphereLight(0x92acd0,0x15110f,.72));const key=new THREE.DirectionalLight(0xc7dbff,3.2);key.position.set(-8,14,10);key.castShadow=true;key.shadow.mapSize.set(mobile()?768:1536,mobile()?768:1536);key.shadow.camera.left=-13;key.shadow.camera.right=13;key.shadow.camera.top=16;key.shadow.camera.bottom=-8;scene.add(key);const warm=new THREE.PointLight(0xffa64f,36,19,2);warm.position.set(0,6,2);scene.add(warm);const rim=new THREE.DirectionalLight(0x5577a8,2.3);rim.position.set(10,7,-10);scene.add(rim);

castle.position.y=-1.25;root.rotation.y=-.48;
let drag=false,lastX=0,targetRot=root.rotation.y;addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX});addEventListener('pointerup',()=>drag=false);addEventListener('pointercancel',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;targetRot+=(e.clientX-lastX)*.0045;lastX=e.clientX});

function progress(){const max=document.documentElement.scrollHeight-innerHeight,p=max>0?clamp(scrollY/max):0;rail.style.height=`${p*100}%`;stageEl.textContent=String(Math.min(6,Math.floor(p*6)+1)).padStart(2,'0');return p}
function disassemble(p){for(const m of modules){const q=smooth(clamp((p-m.userData.start)/(m.userData.end-m.userData.start)));m.position.copy(m.userData.base).addScaledVector(m.userData.off,q);m.rotation.y=m.userData.baseRY+m.userData.rot*q}}
function animate(ms){const t=ms*.001,p=progress();disassemble(p);root.rotation.y+=(targetRot-root.rotation.y)*.055;root.rotation.x=lerp(-.055,.085,p);const z=mobile()?23.5:25.5;camera.position.set(mobile()?.3:1.1,lerp(7.2,9.6,p),z);camera.lookAt(0,lerp(3.7,6.4,p),0);warm.intensity=31+Math.sin(t*1.4)*3;moat.rotation.z=t*.015;for(let i=2;i<atmo.children.length;i++){const s=atmo.children[i];s.scale.setScalar(.75+Math.sin(t*1.4+s.userData.phase)*.18)}renderer.render(scene,camera);requestAnimationFrame(animate)}requestAnimationFrame(animate);
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile()?1.35:1.8));camera.aspect=innerWidth/innerHeight;camera.fov=mobile()?39:34;camera.updateProjectionMatrix()});
