import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s),canvas=$('#scene'),bar=$('.progress i'),stageEl=$('#stageNow');
const mobile=()=>innerWidth<760,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile()?1.5:2));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x0a1525,.03);
const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.1,120);camera.position.set(0,6.2,18.8);
const world=new THREE.Group(),castle=new THREE.Group(),particles=new THREE.Group();scene.add(world);world.add(castle,particles);
scene.add(new THREE.HemisphereLight(0xcfe9ff,0x182433,1.6),new THREE.AmbientLight(0xcadfff,.55));
const sun=new THREE.DirectionalLight(0xfff4d8,2.8);sun.position.set(8,11,7);scene.add(sun);const rim=new THREE.DirectionalLight(0x79bfff,1.6);rim.position.set(-9,5,-8);scene.add(rim);const point=new THREE.PointLight(0xffdca5,24,30,2);point.position.set(0,5.5,1.5);scene.add(point);
const mats={stone:new THREE.MeshStandardMaterial({color:0x9da9b9,roughness:.96,metalness:.03}),dark:new THREE.MeshStandardMaterial({color:0x6d7786,roughness:.96,metalness:.02}),roof:new THREE.MeshStandardMaterial({color:0x394258,roughness:.84,metalness:.05}),gold:new THREE.MeshStandardMaterial({color:0xd8bf75,roughness:.38,metalness:.35}),water:new THREE.MeshStandardMaterial({color:0x3a7395,roughness:.28,metalness:.08,transparent:true,opacity:.9}),wood:new THREE.MeshStandardMaterial({color:0x72553e,roughness:.88,metalness:.04}),rock:new THREE.MeshStandardMaterial({color:0x54616c,roughness:.98,metalness:.02}),grass:new THREE.MeshStandardMaterial({color:0x7d8f78,roughness:1,metalness:0}),glow:new THREE.MeshBasicMaterial({color:0xffd786})};
const pieces=[];
const box=(w,h,d,m)=>new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m),cyl=(r1,r2,h,s,m)=>new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,s),m),cone=(r,h,s,m)=>new THREE.Mesh(new THREE.ConeGeometry(r,h,s),m);
function piece(obj,off,spin=new THREE.Vector3()){obj.userData={origin:obj.position.clone(),off,spin};pieces.push(obj);castle.add(obj);return obj}
function cren(width,depth,count,y){const g=new THREE.Group(),gap=width/count;for(let i=0;i<count;i++)if(i%2===0){const b=box(gap*.62,.28,depth,mats.dark);b.position.set(-width/2+gap*i+gap/2,y,0);g.add(b)}return g}
function turret(r=.48,h=2.2){const g=new THREE.Group(),b=cyl(r,r*1.02,h,14,mats.stone),rf=cone(r*1.4,1.2,14,mats.roof),tip=cyl(.04,.04,.5,6,mats.gold);b.position.y=h/2;rf.position.y=h+.62;tip.position.y=h+1.12;g.add(b,rf,tip);return g}
function tower(r=1.12,h=5.5){const g=new THREE.Group(),b=cyl(r,r*1.05,h,18,mats.stone),ring=cyl(r*1.18,r*1.18,.42,18,mats.dark),rf=cone(r*1.25,2.2,18,mats.roof),sp=cyl(.06,.06,1.2,6,mats.gold),tip=cone(.13,.34,6,mats.gold);b.position.y=h/2;ring.position.y=h+.1;rf.position.y=h+1.35;sp.position.y=h+2.35;tip.position.y=h+2.95;g.add(b,ring,rf,sp,tip);for(let i=0;i<8;i++){const a=i/8*Math.PI*2,c=box(.3,.36,.48,mats.dark);c.position.set(Math.cos(a)*r*1.08,h+.34,Math.sin(a)*r*1.08);c.lookAt(Math.cos(a)*4,h+.34,Math.sin(a)*4);g.add(c)}for(let y=1.25;y<h-1;y+=1.45)for(let i=0;i<4;i++){const a=i/4*Math.PI*2+Math.PI/4,w=box(.18,.52,.06,mats.glow);w.position.set(Math.cos(a)*(r+.03),y,Math.sin(a)*(r+.03));w.lookAt(Math.cos(a)*6,y,Math.sin(a)*6);g.add(w)}return g}
function wall(w,d,h,n=11){const g=new THREE.Group(),b=box(w,h,d,mats.stone);b.position.y=h/2;g.add(b,cren(w,d+.05,n,h+.15));const cols=Math.max(2,Math.floor(w/2.2));for(let i=0;i<cols;i++){const a=box(.16,.6,.06,mats.glow);a.position.set(-w/2+1+i*((w-2)/Math.max(1,cols-1)),h*.52,d/2+.04);g.add(a)}return g}
function windows(g,rows,cols,w,h,startY,z){for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const q=box(w,h,.07,mats.glow);q.position.set((c-(cols-1)/2)*(w*2.4),startY+r*(h*1.9),z);g.add(q)}}
function keep(){const g=new THREE.Group();const terr=box(6.8,.75,6.8,mats.dark),l1=box(5.4,2.4,5.4,mats.stone),l2=box(3.8,2.2,3.8,mats.stone),roofBase=box(4.2,.25,4.2,mats.dark),roof=new THREE.Mesh(new THREE.OctahedronGeometry(2.45,0),mats.roof),spire=cyl(.08,.08,1.5,8,mats.gold),flag=box(.8,.28,.04,mats.gold);terr.position.y=.38;l1.position.y=1.95;l2.position.y=4.2;roofBase.position.y=5.45;roof.scale.y=1.34;roof.position.y=7.15;spire.position.y=8.95;flag.position.set(.44,9.3,0);g.add(terr,l1,l2,roofBase,roof,spire,flag);[['f',0,0,2.7],['b',Math.PI,0,-2.7],['l',Math.PI/2,2.7,0],['r',-Math.PI/2,-2.7,0]].forEach(([,ry,x,z])=>{const c=cren(5.3,.46,8,3.2);c.rotation.y=ry;c.position.set(x,0,z);g.add(c)});windows(g,2,3,.22,.56,1.2,2.74);const wb=new THREE.Group();windows(wb,2,3,.22,.56,1.2,2.74);wb.rotation.y=Math.PI;g.add(wb);const wl=new THREE.Group();windows(wl,2,2,.22,.56,1.2,1.94);wl.rotation.y=Math.PI/2;g.add(wl);const wr=new THREE.Group();windows(wr,2,2,.22,.56,1.2,1.94);wr.rotation.y=-Math.PI/2;g.add(wr);const stair=box(2.2,.16,2.6,mats.dark);stair.position.set(0,.55,4.05);g.add(stair);for(let i=0;i<5;i++){const st=box(1.9-i*.16,.16,.34,mats.dark);st.position.set(0,.18+i*.16,5.2+i*.26);g.add(st)}[[-2.3,-2.3],[2.3,-2.3],[-2.3,2.3],[2.3,2.3]].forEach(([x,z])=>{const t=turret(.42,1.95);t.position.set(x,5.45,z);g.add(t)});return g}
function ground(){const g=new THREE.Group(),island=new THREE.Mesh(new THREE.CylinderGeometry(8.6,9.8,2.2,40),mats.rock),top=new THREE.Mesh(new THREE.CylinderGeometry(7.1,7.8,.75,40),mats.grass),moat=new THREE.Mesh(new THREE.TorusGeometry(7.8,.95,20,80),mats.water);island.position.y=-1.1;top.position.y=.12;moat.rotation.x=Math.PI/2;moat.position.y=-.04;g.add(island,top,moat);for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=6.3+Math.random()*1.3,rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.35+Math.random()*.45,0),mats.dark);rock.position.set(Math.cos(a)*r,.25+Math.random()*.18,Math.sin(a)*r);rock.rotation.set(Math.random()*Math.PI,Math.random()*Math.PI,Math.random()*Math.PI);g.add(rock)}return g}
function bridge(){const g=new THREE.Group(),deck=box(2.2,.18,4.6,mats.wood),l=box(.12,.8,4.5,mats.wood),r=box(.12,.8,4.5,mats.wood);deck.position.set(0,.48,7.2);l.position.set(-1.08,.95,7.2);r.position.set(1.08,.95,7.2);g.add(deck,l,r);for(let i=0;i<8;i++){const p=box(2.06,.05,.38,new THREE.MeshStandardMaterial({color:0x7f5a3f,roughness:.9,metalness:.03}));p.position.set(0,.6,5.5+i*.48);g.add(p)}return g}
function gate(){const g=new THREE.Group(),base=box(3.8,3.25,2.7,mats.stone),arch=box(1.42,1.95,.26,new THREE.MeshStandardMaterial({color:0x1f2836,roughness:1,metalness:0}));base.position.y=1.62;arch.position.set(0,1.08,1.35);g.add(base,arch,cren(3.7,2.78,7,3.4));for(let i=0;i<7;i++){const b=box(.06,1.9,.06,mats.dark);b.position.set(-.54+i*.18,1.06,1.39);g.add(b)}for(let i=0;i<4;i++){const b=box(1.2,.06,.06,mats.dark);b.position.set(0,.32+i*.42,1.39);g.add(b)}const tl=turret(.44,2.2),tr=turret(.44,2.2);tl.position.set(-1.52,3.24,0);tr.position.set(1.52,3.24,0);g.add(tl,tr);return g}
piece(ground(),new THREE.Vector3(0,-2.1,0));piece(keep(),new THREE.Vector3(0,3.6,0),new THREE.Vector3(0,.25,0));const g1=gate();g1.position.set(0,.3,6.25);piece(g1,new THREE.Vector3(0,1.2,4.8),new THREE.Vector3(0,.18,0));piece(bridge(),new THREE.Vector3(0,.15,6.8),new THREE.Vector3(.12,0,0));const wf=wall(8.4,1.12,2.55,11);wf.position.set(0,.35,4.8);piece(wf,new THREE.Vector3(0,.8,4.2));const wb=wall(8.4,1.12,2.55,11);wb.position.set(0,.35,-4.8);piece(wb,new THREE.Vector3(0,1.1,-4.6));const wl=wall(8.4,1.12,2.55,11);wl.rotation.y=Math.PI/2;wl.position.set(-4.8,.35,0);piece(wl,new THREE.Vector3(-4.8,.9,0));const wr=wall(8.4,1.12,2.55,11);wr.rotation.y=Math.PI/2;wr.position.set(4.8,.35,0);piece(wr,new THREE.Vector3(4.8,1,0));[[-4.8,0,-4.8],[4.8,0,-4.8],[-4.8,0,4.8],[4.8,0,4.8]].forEach(([x,y,z])=>{const t=tower();t.position.set(x,y,z);piece(t,new THREE.Vector3(Math.sign(x)*3.6,1.8,Math.sign(z)*3.6),new THREE.Vector3(0,.28*Math.sign(x||1),0))});[[-2.9,0,0],[2.9,0,0],[0,0,-2.9],[0,0,2.9]].forEach(([x,y,z])=>{const t=turret(.58,2.7);t.position.set(x,1.25,z);piece(t,new THREE.Vector3(x*.9,2.2,z*.9),new THREE.Vector3(0,.2,0))});
for(let i=0;i<36;i++){const s=new THREE.Mesh(new THREE.SphereGeometry(Math.random()*.04+.02,6,6),new THREE.MeshBasicMaterial({color:i%3===0?0xcde8ff:0xffffff}));s.position.set((Math.random()-.5)*28,Math.random()*10+2,(Math.random()-.5)*28);s.userData.seed=Math.random()*Math.PI*2;particles.add(s)}
const cloudMat=new THREE.MeshBasicMaterial({color:0xa4c8eb,transparent:true,opacity:.08});for(let i=0;i<8;i++){const c=new THREE.Mesh(new THREE.SphereGeometry(1.6+Math.random()*1.3,14,14),cloudMat);c.scale.set(1.8,.65,1);c.position.set((Math.random()-.5)*28,8+Math.random()*4,(Math.random()-.5)*18);c.userData.seed=Math.random()*Math.PI*2;particles.add(c)}
castle.position.y=-.35;world.rotation.y=-.46;
let dragging=false,lastX=0,targetY=world.rotation.y;addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX});addEventListener('pointerup',()=>dragging=false);addEventListener('pointerleave',()=>dragging=false);addEventListener('pointermove',e=>{if(!dragging)return;targetY+=(e.clientX-lastX)*.0055;lastX=e.clientX});
function explode(p){p=ease(p);pieces.forEach((m,i)=>{const ph=clamp((p-i*.018)/.74,0,1),e=ease(ph);m.position.copy(m.userData.origin).addScaledVector(m.userData.off,e);m.rotation.set(m.userData.spin.x*e,m.userData.spin.y*e,m.userData.spin.z*e)});castle.position.y=mix(-.35,.55,p)}
function scrollP(){const max=document.documentElement.scrollHeight-innerHeight,p=max<=0?0:clamp(scrollY/max,0,1);bar.style.height=`${p*100}%`;stageEl.textContent=String(Math.min(6,Math.floor(p*6)+1)).padStart(2,'0');explode(p);return p}
function loop(t){const time=t*.001,p=scrollP();world.rotation.y+=(targetY-world.rotation.y)*.06;world.rotation.x=mix(-.12,.12,p)+Math.sin(time*.35)*.015;camera.position.x=Math.sin(world.rotation.y+.06)*1.1;camera.position.z=mobile()?17.2:18.8;camera.position.y=mix(6.2,8.2,p);camera.lookAt(0,mix(2.3,4.8,p),0);point.intensity=18+Math.sin(time*1.2)*2.2;sun.position.x=Math.sin(time*.22)*3+8;particles.children.forEach((q,i)=>{q.position.y+=Math.sin(time*.6+q.userData.seed+i)*.002;q.position.x+=Math.sin(time*.14+q.userData.seed)*.0015});renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('resize',()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,mobile()?1.5:2));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});
