import * as THREE from 'three';import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';import{EffectComposer}from'three/addons/postprocessing/EffectComposer.js';import{RenderPass}from'three/addons/postprocessing/RenderPass.js';import{OutputPass}from'three/addons/postprocessing/OutputPass.js';
const canvas=document.querySelector('#scene'),renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;const scene=new THREE.Scene();scene.background=new THREE.Color(0xe7d5ae);const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.05,180);const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new OutputPass());const pm=new THREE.PMREMGenerator(renderer);scene.environment=pm.fromScene(new RoomEnvironment(),.03).texture;pm.dispose();scene.add(new THREE.HemisphereLight(0xfff5d9,0x405466,2.1));const sun=new THREE.DirectionalLight(0xffe0aa,4.2);sun.position.set(-7,12,6);scene.add(sun);
const flat=(c,r=.8,m=.02)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m,flatShading:true}),paper=flat(0xe6d1a8,.96),roadMat=flat(0x444b50,.86),sand=flat(0xd9b56f,.95),sea=flat(0x2e9bb5,.45,.08),green=flat(0x4c7655,.95),brick=flat(0xa34f32,.9),white=flat(0xe9e6d9,.9),city=flat(0xc9c4b6,.88),dark=flat(0x23272a,.7,.18),red=flat(0xc74b3f,.72,.08),glass=flat(0x6c9bad,.3,.25),rock=flat(0x9a7658,.96),night=flat(0x17213a,.55,.15);
const book=new THREE.Group();scene.add(book);const page=new THREE.Mesh(new THREE.BoxGeometry(30,.18,22),paper);page.position.y=-.2;book.add(page);const pathPts=[new THREE.Vector3(-8,0,8),new THREE.Vector3(-3,0,5),new THREE.Vector3(1,0,2),new THREE.Vector3(4,0,-2),new THREE.Vector3(1,0,-6),new THREE.Vector3(-4,0,-8)];const curve=new THREE.CatmullRomCurve3(pathPts,false,'catmullrom',.6);function basis(t){const p=curve.getPointAt(t),tan=curve.getTangentAt(t).normalize(),side=new THREE.Vector3().crossVectors(tan,new THREE.Vector3(0,1,0)).normalize();return{p,tan,side}}
function ribbon(width=3.5){const pos=[],idx=[],n=100;for(let i=0;i<=n;i++){const t=i/n,{p,side}=basis(t),a=p.clone().addScaledVector(side,width/2),b=p.clone().addScaledVector(side,-width/2);pos.push(a.x,.02,a.z,b.x,.02,b.z);if(i<n){const k=i*2;idx.push(k,k+1,k+2,k+1,k+3,k+2)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return new THREE.Mesh(g,roadMat)}book.add(ribbon());for(let t=.04;t<.98;t+=.07){const{p,tan}=basis(t),dash=new THREE.Mesh(new THREE.BoxGeometry(.08,.025,.55),white);dash.position.copy(p);dash.position.y=.05;dash.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),tan);book.add(dash)}
function box(w,h,d,mat,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);return m}function cone(r,h,mat,x,y,z,n=6){const m=new THREE.Mesh(new THREE.ConeGeometry(r,h,n),mat);m.position.set(x,y,z);return m}function cyl(r,h,mat,x,y,z,n=8){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,n),mat);m.position.set(x,y,z);return m}
const scenes=[];function groupAt(t){const g=new THREE.Group(),{p,tan}=basis(t);g.position.copy(p);g.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),tan);book.add(g);scenes.push(g);return g}
// 1 Tran Phu: turquoise bay + beach + lotus-like Tram Huong + skyline
{const g=groupAt(.08);const water=box(10,.05,7,sea,-5,-.05,-1);g.add(water);const beach=box(8,.06,2.4,sand,-4,.0,-.5);g.add(beach);for(let i=0;i<8;i++){g.add(cyl(.06,.8,green,-1.5+i*.55,.4,-2.4,6));g.add(cone(.35,.55,green,-1.5+i*.55,.95,-2.4,7))}for(let i=0;i<7;i++)g.add(box(.55,1.2+i%3*.5,.5,city,2.2+i*.65,.6+(i%3)*.25,-2.4-i*.12));const tram=new THREE.Group();tram.add(cyl(.34,1.9,white,0,.95,0,8));for(let i=0;i<5;i++){const pet=new THREE.Mesh(new THREE.ConeGeometry(.38,.9,4),white);pet.position.set(Math.sin(i*1.256)*.38,1.85,Math.cos(i*1.256)*.38);pet.rotation.z=Math.PI*.5;pet.rotation.y=i*1.256;tram.add(pet)}tram.position.set(.8,0,-2.1);g.add(tram)}
// 2 Long Son: gate + pagoda roof + huge white Buddha on hill
{const g=groupAt(.3);const hill=new THREE.Mesh(new THREE.ConeGeometry(4,1.7,9),green);hill.position.set(2,.65,-2);g.add(hill);const temple=box(3,.8,1.7,white,-2,.4,-1);g.add(temple);const roof=new THREE.Mesh(new THREE.ConeGeometry(2.2,.8,4),red);roof.scale.z=.65;roof.rotation.y=Math.PI/4;roof.position.set(-2,1.15,-1);g.add(roof);const buddha=new THREE.Group();buddha.add(cyl(.8,.45,white,0,.22,0,12));buddha.add(cyl(.48,1.25,white,0,1.0,0,10));const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.42,1),white);head.position.y=1.85;buddha.add(head);const halo=new THREE.Mesh(new THREE.TorusGeometry(.65,.07,8,18),white);halo.position.y=1.85;halo.rotation.y=Math.PI/2;buddha.add(halo);buddha.scale.set(1.35,1.35,1.35);buddha.position.set(2,1.4,-2);g.add(buddha)}
// 3 Po Nagar: four unmistakable red-brick Cham towers
{const g=groupAt(.52);for(const [x,z,s]of[[-2,-1,1],[0,-1.3,1.35],[2,-.8,.85],[1.2,1,.72]]){const tower=new THREE.Group();tower.add(box(1.1,2.5*s,1.1,brick,0,1.25*s,0));tower.add(cone(.78,1.5*s,brick,0,3.2*s,0,5));const door=box(.35,.9*s,.05,dark,0,.55*s,-.56);tower.add(door);tower.position.set(x,0,z);g.add(tower)}for(let i=0;i<6;i++)g.add(cyl(.09,.8,green,-3+i*1.1,.4,2.2,6))}
// 4 Hon Chong: giant stacked granite boulders + sea + mountain backdrop
{const g=groupAt(.72);g.add(box(9,.05,6,sea,-2,-.06,-1));for(let i=0;i<16;i++){const r=new THREE.Mesh(new THREE.DodecahedronGeometry(.65+(i%4)*.22,0),rock);r.scale.set(1.4,.75,1);r.position.set(-3+(i%6)*1.15,.45+(i>11?1.0:0),-1+(i%3)*.75);r.rotation.set(i*.2,i*.35,0);g.add(r)}const hero=new THREE.Mesh(new THREE.DodecahedronGeometry(1.15,0),rock);hero.position.set(.2,2.15,-.6);hero.rotation.z=.28;g.add(hero);g.add(cone(3.5,3.1,green,5,1.5,-3,7))}
// 5 Nha Trang night: beachfront skyline + glowing Tram Huong silhouette
{const g=groupAt(.91);g.add(box(9,.05,5,sea,-3,-.05,-1));for(let i=0;i<10;i++){const m=i%3===0?new THREE.MeshStandardMaterial({color:0x17213a,emissive:0x45d8ff,emissiveIntensity:.8,flatShading:true}):night;g.add(box(.65,1.8+(i%4)*.65,.65,m,-1+i*.85,.9+(i%4)*.32,-2.5))}const glow=new THREE.MeshStandardMaterial({color:0xf1d2b2,emissive:0xff9b61,emissiveIntensity:2,flatShading:true});g.add(cyl(.42,2.4,glow,-2,1.2,-1.2,8))}
// car: deliberately readable, compact low-poly touring coupe
const car=new THREE.Group();car.add(box(1.35,.35,2.65,red,0,.42,0));const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.05,.52,1.15),glass);cabin.position.set(0,.78,.12);car.add(cabin);car.add(box(1.2,.08,.35,dark,0,.26,-1.25));const wheels=[];for(const[x,z]of[[-.68,-.75],[.68,-.75],[-.68,.78],[.68,.78]]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.25,.25,.18,10),dark);w.rotation.z=Math.PI/2;w.position.set(x,.28,z);car.add(w);wheels.push(w)}book.add(car);
const folio=document.querySelector('#folio'),place=document.querySelector('#place'),meta=document.querySelector('#meta'),chapters=[...document.querySelectorAll('.chapter')];let target=.01,p=.01,last=0,vel=0,camPos=new THREE.Vector3(),camQ=new THREE.Quaternion(),first=true;const mat4=new THREE.Matrix4(),q=new THREE.Quaternion(),UP=new THREE.Vector3(0,1,0),FWD=new THREE.Vector3(0,0,-1),clock=new THREE.Clock();function scroll(){const total=Math.max(document.documentElement.scrollHeight-innerHeight,1);target=.01+scrollY/total*.98;vel=Math.min(1,vel+Math.abs(scrollY-last)/500);last=scrollY}addEventListener('scroll',scroll,{passive:true});scroll();
function render(){const dt=Math.min(clock.getDelta(),.04);p=THREE.MathUtils.damp(p,target,3.2,dt);vel=THREE.MathUtils.damp(vel,0,3,dt);const idx=Math.min(4,Math.floor(p*5)),local=p*5-idx,{p:cp,tan,side}=basis(p);car.position.copy(cp);car.position.y=.12;car.quaternion.slerp(q.setFromUnitVectors(FWD,tan),1-Math.exp(-dt*10));wheels.forEach(w=>w.rotation.x-=dt*(4+vel*18));folio.textContent=String(idx+1).padStart(2,'0');place.textContent=chapters[idx].dataset.name;meta.textContent=chapters[idx].dataset.meta;
// pop-up book choreography: active landmark rises from the page, neighbours fold down
scenes.forEach((g,i)=>{const d=Math.abs(i-idx),rise=d===0?1:d===1?.12:0;g.scale.y=THREE.MathUtils.damp(g.scale.y,rise,4.2,dt);g.rotation.x=THREE.MathUtils.damp(g.rotation.x,d===0?0:-Math.PI*.48,4.2,dt);g.visible=d<2});
// page turn at chapter boundary: whole book tilts subtly like a physical spread turning
const fold=Math.sin(Math.min(1,Math.min(local,1-local)*5)*Math.PI)*.035;book.rotation.z=THREE.MathUtils.damp(book.rotation.z,(idx%2?1:-1)*fold,5,dt);
// iOS-safe invariant: camera always behind/above car; car + road occupy central 70% of frame
const back=innerWidth<700?7.8:8.8,height=innerWidth<700?5.3:4.8,sideOff=(idx%2?-.8:.8);const desired=cp.clone().addScaledVector(tan,-back).addScaledVector(UP,height).addScaledVector(side,sideOff);if(first){camPos.copy(desired);first=false}else camPos.lerp(desired,1-Math.exp(-dt*3.4));camera.position.copy(camPos);const ahead=curve.getPointAt(Math.min(1,p+.055));const focus=cp.clone().lerp(ahead,.55);focus.y=.25;mat4.lookAt(camera.position,focus,UP);const dq=new THREE.Quaternion().setFromRotationMatrix(mat4);camQ.slerp(dq,1-Math.exp(-dt*4));camera.quaternion.copy(camQ);camera.fov=THREE.MathUtils.damp(camera.fov,innerWidth<700?58:48,4,dt);camera.updateProjectionMatrix();composer.render();requestAnimationFrame(render)}render();setTimeout(()=>document.querySelector('#loader').classList.add('done'),700);addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();composer.setSize(innerWidth,innerHeight)});
