(()=>{
  const FALLBACK_LIBRARY=[{id:'aura-scroll-product-story',index:'001',title:'Scroll Product Story',family:['product','scroll','typography','interaction'],status:'production',live:'../aura-eclipse-scroll/',preview:'../aura-eclipse-scroll/?frame=.55&library=1',source:'https://github.com/louisalviss/valentine/tree/main/aura-eclipse-scroll',description:'A pinned product narrative with one continuous hero object, scene wipe, editorial type layering and interactive feature hotspots.',bestFor:['Premium hardware'],stack:['HTML','CSS','JavaScript'],tags:['Pinned scroll','Layered type'],primitives:[{name:'ScrollProduct',description:'Moves one focal product through narrative compositions.'}]}];
  const FALLBACK_QUALITY={version:'1.0',statusValue:{pass:1,review:.5,fail:0},weights:{distinctGrammar:18,routeIntegrity:8,responsive:12,interaction:10,reducedMotion:10,assetRights:14,dependencies:8,performance:10,accessibility:10},critical:['distinctGrammar','routeIntegrity','responsive','assetRights'],thresholds:{promote:80,keepAsLab:65,review:50,clientReady:90},patterns:{'aura-scroll-product-story':{gates:{distinctGrammar:'pass',routeIntegrity:'pass',responsive:'pass',interaction:'pass',reducedMotion:'review',assetRights:'pass',dependencies:'pass',performance:'pass',accessibility:'review'},lastVerified:'2026-08-24'}}};
  const $=id=>document.getElementById(id),grid=$('patternGrid'),filters=$('filters'),searchInput=$('searchInput'),resultCount=$('resultCount'),patternCount=$('patternCount'),readyCount=$('readyCount'),primitiveCount=$('primitiveCount'),patternDialog=$('patternDialog'),useDialog=$('useDialog'),aboutDialog=$('aboutDialog'),detailFrame=$('detailFrame'),detailIndex=$('detailIndex'),detailFamily=$('detailFamily'),detailTitle=$('detailTitle'),detailDescription=$('detailDescription'),detailScore=$('detailScore'),detailDecision=$('detailDecision'),qualityGates=$('qualityGates'),qualityNote=$('qualityNote'),primitiveList=$('primitiveList'),bestFor=$('bestFor'),stack=$('stack'),openLive=$('openLive'),openSource=$('openSource'),usePattern=$('usePattern'),useForm=$('useForm'),briefOutput=$('briefOutput'),briefText=$('briefText'),copyBrief=$('copyBrief');
  let library=FALLBACK_LIBRARY,quality=FALLBACK_QUALITY,activeFilter='all',activePattern=library[0],previewObserver=null;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const normalize=v=>String(v||'').toLowerCase().trim();
  function qualityFor(pattern){
    const entry=quality.patterns?.[pattern.id]||{gates:{}};
    const score=Math.round(Object.entries(quality.weights||{}).reduce((sum,[key,w])=>sum+w*((quality.statusValue||{})[entry.gates?.[key]]??0),0));
    let decision='REVIEW';
    if(pattern.supersededBy||pattern.duplicateOf)decision='SUPERSEDE';
    else if(entry.gates?.distinctGrammar==='fail'||score<(quality.thresholds?.review??50))decision='DELETE';
    else if((quality.critical||[]).some(k=>entry.gates?.[k]!=='pass'))decision='REVIEW';
    else if(score>=(quality.thresholds?.promote??80))decision='PROMOTE';
    else if(score>=(quality.thresholds?.keepAsLab??65))decision='KEEP AS LAB';
    const ready=decision==='PROMOTE'&&score>=(quality.thresholds?.clientReady??90)&&['routeIntegrity','responsive','assetRights','dependencies','performance'].every(k=>entry.gates?.[k]==='pass');
    const debt=Object.entries(entry.gates||{}).filter(([,v])=>v!=='pass');
    return {entry,score,decision,ready,debt};
  }
  function hydrateStats(){
    patternCount.textContent=String(library.length).padStart(2,'0');
    readyCount.textContent=String(library.filter(p=>qualityFor(p).ready).length).padStart(2,'0');
    const primitives=new Set(library.flatMap(p=>(p.primitives||[]).map(x=>x.name)));primitiveCount.textContent=String(primitives.size).padStart(2,'0');
  }
  function filtered(){
    const q=normalize(searchInput.value);
    return library.filter(pattern=>{const family=pattern.family||[],qv=qualityFor(pattern);const filterOk=activeFilter==='all'||(activeFilter==='ready'?qv.ready:family.includes(activeFilter));if(!filterOk)return false;if(!q)return true;const hay=[pattern.title,pattern.description,qv.decision,String(qv.score),...family,...(pattern.tags||[]),...(pattern.bestFor||[]),...(pattern.primitives||[]).flatMap(x=>[x.name,x.description])].join(' ').toLowerCase();return hay.includes(q);});
  }
  function card(pattern){
    const q=qualityFor(pattern),tags=(pattern.tags||[]).slice(0,4).map(tag=>`<span>${esc(tag)}</span>`).join(''),preview=pattern.preview||pattern.live,state=q.ready?'ready':q.decision==='REVIEW'?'review':'lab';
    return `<article class="pattern-card" tabindex="0" role="button" aria-label="Open ${esc(pattern.title)}" data-pattern="${esc(pattern.id)}"><div class="card-meta"><span>${esc(pattern.index)} / ${esc((pattern.family||[])[0]||'pattern')}</span><span class="quality-badge ${state}"><b>${q.score}</b> · ${q.ready?'CLIENT READY':q.decision}</span></div><div class="preview-shell"><iframe src="about:blank" data-src="${esc(preview)}" title="${esc(pattern.title)} preview" loading="lazy" tabindex="-1"></iframe><div class="preview-shade"></div><div class="preview-badge">Open pattern ↗</div></div><div class="card-body"><div><h3>${esc(pattern.title)}</h3><p>${esc(pattern.description)}</p></div><div class="tag-list">${tags}</div></div></article>`;
  }
  function armPreviews(){if(previewObserver){previewObserver.disconnect();previewObserver=null;}const frames=[...grid.querySelectorAll('iframe[data-src]')];if(!frames.length)return;const load=f=>{if(!f.dataset.src)return;f.src=f.dataset.src;f.removeAttribute('data-src');};if(!('IntersectionObserver'in window)){frames.forEach(load);return;}previewObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){load(e.target);previewObserver.unobserve(e.target);}}),{rootMargin:'320px 0px'});frames.forEach(f=>previewObserver.observe(f));}
  function render(){const items=filtered();resultCount.textContent=`${String(items.length).padStart(2,'0')} ${items.length===1?'result':'results'}`;grid.innerHTML=items.length?items.map(card).join(''):`<div class="empty">No matching curated pattern yet.</div>`;armPreviews();}
  function showPattern(pattern){
    activePattern=pattern;const q=qualityFor(pattern);detailIndex.textContent=pattern.index||'001';detailFamily.textContent=(pattern.family||[]).slice(0,3).join(' / ').toUpperCase();detailTitle.textContent=pattern.title;detailDescription.textContent=pattern.description||'';detailScore.textContent=String(q.score);detailDecision.textContent=q.ready?'CLIENT READY':q.decision;detailDecision.dataset.state=q.ready?'ready':q.decision==='REVIEW'?'review':'lab';qualityGates.innerHTML=Object.entries(q.entry.gates||{}).map(([k,v])=>`<span class="gate ${esc(v)}"><b>${esc(k.replace(/([A-Z])/g,' $1'))}</b>${esc(v)}</span>`).join('');qualityNote.textContent=q.entry.note||`Last verified ${q.entry.lastVerified||'—'}`;primitiveList.innerHTML=(pattern.primitives||[]).map(p=>`<div class="primitive-row"><span class="primitive-chip">${esc(p.name)}</span><p>${esc(p.description)}</p></div>`).join('');bestFor.textContent=(pattern.bestFor||[]).join(' · ');stack.textContent=(pattern.stack||[]).join(' / ');openLive.href=pattern.live;openSource.href=pattern.source||pattern.live;usePattern.textContent=q.ready?'Use pattern':'Use pattern · review';detailFrame.src=pattern.live;patternDialog.showModal();
  }
  function closePattern(){if(patternDialog.open)patternDialog.close();detailFrame.src='about:blank';}
  filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;filters.querySelectorAll('.filter').forEach(el=>el.classList.toggle('active',el===b));render();});searchInput.addEventListener('input',render);grid.addEventListener('click',e=>{const el=e.target.closest('[data-pattern]');if(!el)return;const p=library.find(x=>x.id===el.dataset.pattern);if(p)showPattern(p);});grid.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const el=e.target.closest('[data-pattern]');if(!el)return;e.preventDefault();const p=library.find(x=>x.id===el.dataset.pattern);if(p)showPattern(p);});
  document.querySelector('[data-close-dialog]').addEventListener('click',closePattern);patternDialog.addEventListener('click',e=>{if(e.target===patternDialog)closePattern();});patternDialog.addEventListener('cancel',e=>{e.preventDefault();closePattern();});
  usePattern.addEventListener('click',()=>{closePattern();briefOutput.hidden=true;useDialog.showModal();});document.querySelector('[data-close-use]').addEventListener('click',()=>useDialog.close());useDialog.addEventListener('click',e=>{if(e.target===useDialog)useDialog.close();});
  useForm.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(useForm).entries()),p=activePattern,q=qualityFor(p),debts=q.debt.length?q.debt.map(([k,v])=>`- ${k}: ${v}`).join('\n'):'- none';const brief=`BUILD FROM WEB MOTION LIBRARY\n\nPattern: ${p.title} [${p.index}]\nLive reference: ${new URL(p.live,location.href).href}\nQuality score: ${q.score}/100\nDecision: ${q.decision}\nClient readiness: ${q.ready?'READY':'REVIEW REQUIRED'}\nQuality debt:\n${debts}\n\nClient / brand: ${data.brand}\nProduct / offer: ${data.product}\nIndustry: ${data.industry||'Not specified'}\nArt direction: ${data.direction}\n\nPreserve these interaction primitives:\n${(p.primitives||[]).map(x=>`- ${x.name}: ${x.description}`).join('\n')}\n\nChange for this build:\n${data.changes||'- Replace brand, copy, product asset, palette and feature content while preserving the interaction grammar.'}\n\nAcceptance:\n- Resolve client-specific quality debt before launch.\n- Keep one dominant focal idea per viewport.\n- Preserve readable hierarchy at 390x844, 768x1024 and 1440x900.\n- Recreate/self-host assets rather than hotlink unstable media.\n- Reduced motion must remain usable.\n- Do not copy the reference surface literally when a better brand-specific composition is possible.`;briefText.textContent=brief;briefOutput.hidden=false;briefOutput.scrollIntoView({behavior:'smooth',block:'nearest'});});
  copyBrief.addEventListener('click',async()=>{const text=briefText.textContent;try{await navigator.clipboard.writeText(text);copyBrief.textContent='Copied';}catch{const r=document.createRange();r.selectNodeContents(briefText);const s=getSelection();s.removeAllRanges();s.addRange(r);document.execCommand('copy');copyBrief.textContent='Copied';}setTimeout(()=>copyBrief.textContent='Copy brief',1200);});
  $('openAbout').addEventListener('click',()=>aboutDialog.showModal());document.querySelector('[data-close-about]').addEventListener('click',()=>aboutDialog.close());aboutDialog.addEventListener('click',e=>{if(e.target===aboutDialog)aboutDialog.close();});
  async function load(){try{const [lr,qr]=await Promise.all([fetch('./library.json',{cache:'no-store'}),fetch('./quality.json',{cache:'no-store'})]);if(lr.ok){const d=await lr.json();if(Array.isArray(d.patterns)&&d.patterns.length)library=d.patterns;}if(qr.ok)quality=await qr.json();}catch{}hydrateStats();render();}load();
})();
