import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';

const canvas=document.querySelector('#scene'),loader=document.querySelector('#loader'),sections=[...document.querySelectorAll('section')],step=document.querySelector('#step'),place=document.querySelector('#place'),meta=document.querySelector('#meta');
const coarse=matchMedia('(pointer:coarse)').matches,lowPower=coarse||(navigator.hardwareConcurrency||8)<=4,clamp=THREE.MathUtils.clamp,damp=THREE.MathUtils.damp,UP=new THREE.Vector3(0,1,0),FORWARD=new THREE.Vector3(0,0,-1);
const renderer=new THREE.WebGLRenderer({canvas,antialias:!lowPower,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,lowPower?1.05:1.55));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=!lowPower;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb9ddea);scene.fog=new THREE.FogExp2(0xb9ddea,.0065);const camera=new THREE.PerspectiveCamera(coarse?56:49,innerWidth/innerHeight,.04,420);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new OutputPass());
scene.add(new THREE.HemisphereLight(0xf7fbff,0x6f7b61,2.05));const sun=new THREE.DirectionalLight(0xfff1d5,4.2);sun.position.set(-8,15,5);sun.castShadow=!lowPower;scene.add(sun);
const flat=(color,rough=.82,metal=.02)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,flatShading:true});
const paper=(color)=>new THREE.MeshStandardMaterial({color,roughness:.9,metalness:0,flatShading:true,side:THREE.DoubleSide});
const pts=[new THREE.Vector3(0,.35,12),new THREE.Vector3(-2,.45,-8),new THREE.Vector3(2,.5,-30),new THREE.Vector3(-4,.58,-52),new THREE.Vector3(-8,.7,-75),new THREE.Vector3(-2,.8,-98),new THREE.Vector3(6,.9,-120),new THREE.Vector3(11,1.1,-145),new THREE.Vector3(5,1.3,-170),new THREE.Vector3(-5,1.55,-195),new THREE.Vector3(-9,1.8,-220),new THREE.Vector3(-3,2,-248),new THREE.Vector3(4,2.3,-275),new THREE.Vector3(0,2.6,-302)];
const curve=new THREE.CatmullRomCurve3(pts,false,'catmullrom',.58);
function basis(t){t=clamp(t,0,1);const p=curve.getPointAt(t),tangent=curve.getTangentAt(t).normalize();let side=new THREE.Vector3().crossVectors(tangent,UP).normalize();if(side.lengthSq()<.2)side.set(1,0,0);const normal=new THREE.Vector3().crossVectors(side,tangent).normalize();return{p,tangent,side,normal}}
function ribbon(width,mat,y=0){const seg=760,pos=[],idx=[];for(let i=0;i<=seg;i++){const t=i/seg,{p,side,normal}=basis(t),l=p.clone().addScaledVector(side,width/2).addScaledVector(normal,y),r=p.clone().addScaledVector(side,-width/2).addScaledVector(normal,y);pos.push(l.x,l.y,l.z,r.x,r.y,r.z);if(i<seg){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,b,c,b,d,c)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();const m=new THREE.Mesh(g,mat);m.receiveShadow=true;scene.add(m);return m}
ribbon(44,paper(0xe9dfc8),-.22);ribbon(6.3,flat(0x4b5660,.9),.01);for(const off of[-3.15,3.15]){const ls=[];for(let i=0;i<=420;i++){const {p,side,normal}=basis(i/420);ls.push(p.clone().addScaledVector(side,off).addScaledVector(normal,.035))}scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(ls),new THREE.LineBasicMaterial({color:0xf5f0dd,transparent:true,opacity:.82})))}
for(let t=.012;t<.99;t+=.024){const {p,tangent,normal}=basis(t),d=new THREE.Mesh(new THREE.BoxGeometry(.08,.02,.72),new THREE.MeshBasicMaterial({color:0xf5f0dd}));d.position.copy(p).addScaledVector(normal,.04);d.quaternion.setFromUnitVectors(FORWARD,tangent);scene.add(d)}
for(let t=.08;t<.98;t+=.1){const {p,tangent}=basis(t),seam=new THREE.Mesh(new THREE.BoxGeometry(38,.015,.045),new THREE.MeshBasicMaterial({color:0xc7bda9,transparent:true,opacity:.45}));seam.position.copy(p).addScaledVector(UP,-.18);seam.quaternion.setFromUnitVectors(FORWARD,tangent);seam.rotateY(Math.PI/2);scene.add(seam)}
const sea=new THREE.Mesh(new THREE.PlaneGeometry(120,210,28,34),paper(0x2f9cc8));sea.rotation.x=-Math.PI/2;sea.position.set(-38,-.35,-82);scene.add(sea);const beach=new THREE.Mesh(new THREE.PlaneGeometry(18,170),paper(0xe8cf96));beach.rotation.x=-Math.PI/2;beach.rotation.z=.04;beach.position.set(-12,-.24,-70);scene.add(beach);
for(let i=0;i<55;i++){const t=.02+Math.random()*.25,{p,side}=basis(t),s=i%2?1:-1;if(s>0){const h=2+Math.random()*7,m=new THREE.Mesh(new THREE.BoxGeometry(.7+Math.random()*1.2,h,.7+Math.random()),paper(i%4?0xf2e5cf:0xdad1c6));m.position.copy(p).addScaledVector(side,5+Math.random()*7);m.position.y+=h/2-.1;scene.add(m)}else if(i<30){makePalm(t,-(4.5+Math.random()*2.5),1.7+Math.random())}}
function makePalm(t,off,s=2.2){const {p,side}=basis(t),g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.07,.11,s,5),flat(0x8f6846));tr.position.y=s/2;g.add(tr);for(let k=0;k<6;k++){const leaf=new THREE.Mesh(new THREE.ConeGeometry(.12,.9,3),flat(0x2c7d55));leaf.position.y=s;leaf.rotation.z=Math.PI/2;leaf.rotation.y=k*Math.PI/3;leaf.position.x=Math.cos(k*Math.PI/3)*.28;leaf.position.z=Math.sin(k*Math.PI/3)*.28;g.add(leaf)}g.position.copy(p).addScaledVector(side,off);scene.add(g)}
function makeCar(){const g=new THREE.Group(),red=flat(0xe95542,.42,.08),dark=flat(0x151a1f,.38,.45),glass=flat(0x76a2b7,.24,.25),white=flat(0xf7f6ed,.3,.05);const body=new THREE.Mesh(new THREE.BoxGeometry(1.8,.38,3.2),red);body.position.y=.48;g.add(body);const hood=new THREE.Mesh(new THREE.BoxGeometry(1.62,.22,1.15),red);hood.position.set(0,.72,-1.15);hood.rotation.x=-.08;g.add(hood);const cab=new THREE.Mesh(new THREE.BoxGeometry(1.2,.58,1.25),glass);cab.position.set(0,.92,.12);cab.rotation.x=-.06;g.add(cab);const roof=new THREE.Mesh(new THREE.BoxGeometry(1.02,.08,.9),dark);roof.position.set(0,1.23,.12);g.add(roof);for(const [x,z] of [[-.86,-1],[.86,-1],[-.86,1],[.86,1]]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.31,.31,.22,10),dark);w.rotation.z=Math.PI/2;w.position.set(x,.34,z);g.add(w)}for(const x of[-.58,.58]){const l=new THREE.Mesh(new THREE.BoxGeometry(.32,.07,.04),white);l.position.set(x,.68,-1.63);g.add(l)}return g}const car=makeCar();scene.add(car);
const popups=[];
function popupAt(t,sideOffset,label,builder){const {p,tangent,side}=basis(t),anchor=new THREE.Group();anchor.position.copy(p).addScaledVector(side,sideOffset);anchor.quaternion.setFromUnitVectors(FORWARD,tangent);const hinge=new THREE.Group();hinge.rotation.x=-Math.PI/2;anchor.add(hinge);builder(hinge);const tag=makeLabel(label);tag.position.set(0,.15,.1);hinge.add(tag);scene.add(anchor);popups.push({t,hinge});return anchor}
function makeLabel(text){const c=document.createElement('canvas');c.width=512;c.height=128;const q=c.getContext('2d');q.fillStyle='#f6efdf';q.fillRect(0,0,c.width,c.height);q.strokeStyle='#bda98e';q.lineWidth=6;q.strokeRect(3,3,c.width-6,c.height-6);q.fillStyle='#23343c';q.font='700 40px system-ui';q.textAlign='center';q.textBaseline='middle';q.fillText(text,256,64);const tex=new THREE.CanvasTexture(c);const s=new THREE.Mesh(new THREE.PlaneGeometry(3.3,.82),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide}));s.position.y=3.4;return s}
function buildTram(g){const base=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.45,.45,6),paper(0xe7d8bf));base.position.y=.22;g.add(base);const core=new THREE.Mesh(new THREE.CylinderGeometry(.62,.85,3.5,6),paper(0xe8d6c6));core.position.y=1.9;g.add(core);for(let i=0;i<6;i++){const petal=new THREE.Mesh(new THREE.ConeGeometry(.55,2.4,4),paper(i%2?0xf1e9dc:0xdcae9e));petal.position.set(Math.cos(i*Math.PI/3)*.72,2.55,Math.sin(i*Math.PI/3)*.72);petal.rotation.z=Math.PI*.08;petal.rotation.y=-i*Math.PI/3;g.add(petal)}const tip=new THREE.Mesh(new THREE.ConeGeometry(.34,1.4,5),paper(0xf4eadc));tip.position.y=4.55;g.add(tip)}
function buildBuddha(g){const hill=new THREE.Mesh(new THREE.ConeGeometry(3.2,1.3,7),paper(0x6d8f60));hill.position.y=.6;g.add(hill);const lotus=new THREE.Mesh(new THREE.CylinderGeometry(1.15,1.45,.6,12),paper(0xf0eee5));lotus.position.y=1.45;g.add(lotus);const body=new THREE.Mesh(new THREE.SphereGeometry(1.05,10,7),paper(0xf5f3ec));body.scale.set(1,.95,.78);body.position.y=2.45;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.48,10,7),paper(0xf7f5ef));head.position.y=3.55;g.add(head);const ushnisha=new THREE.Mesh(new THREE.SphereGeometry(.18,8,5),paper(0xf7f5ef));ushnisha.position.y=4.02;g.add(ushnisha);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.2,.7,4),paper(0xb14f3d));roof.rotation.y=Math.PI/4;roof.position.set(-2,1.45,.2);g.add(roof)}
function buildPoNagar(g){const brick=paper(0xa8542f),dark=paper(0x7e3a25);for(const [x,h,s] of [[0,4.6,1.15],[-2,3.5,.9],[2.1,3.1,.82]]){const b=new THREE.Mesh(new THREE.BoxGeometry(1.5*s,2.9*s,1.45*s),brick);b.position.set(x,1.45*s,0);g.add(b);const roof1=new THREE.Mesh(new THREE.ConeGeometry(1.15*s,1.3*s,4),brick);roof1.rotation.y=Math.PI/4;roof1.position.set(x,3.55*s,0);g.add(roof1);const roof2=new THREE.Mesh(new THREE.ConeGeometry(.72*s,.9*s,4),dark);roof2.rotation.y=Math.PI/4;roof2.position.set(x,4.45*s,0);g.add(roof2);const door=new THREE.Mesh(new THREE.BoxGeometry(.45*s,.95*s,.04),dark);door.position.set(x,.8*s,-.75*s);g.add(door)}}
function buildHonChong(g){const sand=new THREE.Mesh(new THREE.PlaneGeometry(7,4),paper(0xe5c883));sand.rotation.x=-Math.PI/2;sand.position.y=.02;g.add(sand);const rock=flat(0xb68a63);for(let i=0;i<15;i++){const r=new THREE.Mesh(new THREE.DodecahedronGeometry(.55+Math.random()*.65,0),rock);r.scale.set(1.2,.8+Math.random()*.5,.9);r.position.set((Math.random()-.5)*5,.35+Math.random()*.65,(Math.random()-.5)*2.6);r.rotation.set(Math.random(),Math.random(),Math.random());g.add(r)}const big=new THREE.Mesh(new THREE.DodecahedronGeometry(1.2,0),rock);big.scale.set(1.45,.78,1);big.position.set(.6,1.15,.2);big.rotation.z=.18;g.add(big)}
function buildBeach(g){for(let i=0;i<8;i++){const palm=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.06,.1,2.1,5),flat(0x8b6545));tr.position.y=1.05;palm.add(tr);for(let k=0;k<5;k++){const lf=new THREE.Mesh(new THREE.ConeGeometry(.11,.8,3),flat(0x2c7d55));lf.rotation.z=Math.PI/2;lf.rotation.y=k*Math.PI*2/5;lf.position.y=2.1;palm.add(lf)}palm.position.set(-3+i*.8,0,(i%2)*.5);g.add(palm)}}
popupAt(.11,-6.8,'Bờ biển Trần Phú',buildBeach);popupAt(.28,-7.2,'Tháp Trầm Hương',buildTram);popupAt(.49,7.5,'Chùa Long Sơn',buildBuddha);popupAt(.70,-7.5,'Tháp Bà Po Nagar',buildPoNagar);popupAt(.89,-7.2,'Hòn Chồng',buildHonChong);
let target=.005,progress=.005,velocity=0,lastY=scrollY,camPos=new THREE.Vector3(),first=true;const carQ=new THREE.Quaternion(),camQ=new THREE.Quaternion(),lookM=new THREE.Matrix4(),clock=new THREE.Clock();
function onScroll(){const total=Math.max(document.documentElement.scrollHeight-innerHeight,1);target=.005+(scrollY/total)*.99;velocity=Math.min(1,velocity+Math.abs(scrollY-lastY)/700);lastY=scrollY}addEventListener('scroll',onScroll,{passive:true});onScroll();
function smoothstep(a,b,x){x=clamp((x-a)/(b-a),0,1);return x*x*(3-2*x)}
function updatePopup(pp){const d=progress-pp.t;let rise;if(d<-.08)rise=0;else if(d<-.015)rise=smoothstep(-.08,-.015,d);else if(d<.065)rise=1;else if(d<.12)rise=1-smoothstep(.065,.12,d);else rise=0;pp.hinge.rotation.x=-Math.PI/2+(Math.PI/2)*rise;pp.hinge.scale.y=.98+.02*rise}
function syncHud(){const total=Math.max(document.documentElement.scrollHeight-innerHeight,1),p=scrollY/total,idx=clamp(Math.floor(p*sections.length),0,sections.length-1),s=sections[idx];step.textContent=String(idx+1).padStart(2,'0');place.textContent=s.dataset.place;meta.textContent=s.dataset.meta;document.documentElement.style.setProperty('--progress',(p*100)+'%')}
function render(){requestAnimationFrame(render);const dt=Math.min(clock.getDelta(),.04);progress=damp(progress,target,3.2,dt);velocity=damp(velocity,0,3,dt);syncHud();const {p,tangent,side,normal}=basis(progress);car.position.copy(p).addScaledVector(normal,.03);carQ.setFromUnitVectors(FORWARD,tangent);car.quaternion.slerp(carQ,1-Math.exp(-dt*9));popups.forEach(updatePopup);const back=coarse?9.8:9.0,height=coarse?4.4:4.0,sideOffset=coarse?1.35:1.7;const desired=p.clone().addScaledVector(tangent,-back).addScaledVector(normal,height).addScaledVector(side,sideOffset);if(first)camPos.copy(desired);else camPos.lerp(desired,1-Math.exp(-dt*3.5));camera.position.copy(camPos);const focus=curve.getPointAt(clamp(progress+(coarse?.065:.075),0,1)).addScaledVector(UP,.55);lookM.lookAt(camera.position,focus,UP);camQ.setFromRotationMatrix(lookM);camera.quaternion.slerp(camQ,first?1:1-Math.exp(-dt*4));first=false;camera.fov=damp(camera.fov,(coarse?56:49)+velocity*2.2,3,dt);camera.updateProjectionMatrix();composer.render()}
render();setTimeout(()=>loader.classList.add('done'),450);addEventListener('resize',()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,lowPower?1.05:1.55));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();composer.setSize(innerWidth,innerHeight)});