import {THREE,scene,lowPower,basisAt,boxAt,rockAt,FORWARD} from './core.js';
const flat=(o)=>new THREE.MeshStandardMaterial({...o,flatShading:true});
const waterGeo=new THREE.PlaneGeometry(190,88,46,18);waterGeo.rotateX(-Math.PI/2);const wp=waterGeo.attributes.position;for(let i=0;i<wp.count;i++)wp.setY(i,(Math.random()-.5)*.15);waterGeo.computeVertexNormals();
export const water=new THREE.Mesh(waterGeo,new THREE.MeshPhysicalMaterial({color:0x19728f,roughness:.2,metalness:.14,clearcoat:.35,flatShading:true}));water.position.set(0,-1.15,-28);scene.add(water);
const pylonMat=flat({color:0xc4c8c2,roughness:.9}),railMat=flat({color:0xe6ece9,roughness:.52,metalness:.12});
for(let t=.012;t<.195;t+=.015){const {p,tangent,side}=basisAt(t);[-1,1].forEach(s=>{const py=new THREE.Mesh(new THREE.CylinderGeometry(.14,.19,2.7,6),pylonMat);py.position.copy(p).addScaledVector(side,s*2.35);py.position.y-=1.15;scene.add(py);const r=new THREE.Mesh(new THREE.BoxGeometry(.07,.34,1.9),railMat);r.position.copy(p).addScaledVector(side,s*2.78);r.position.y+=.19;r.quaternion.setFromUnitVectors(FORWARD,tangent);scene.add(r)})}
const islandMat=flat({color:0x406f63,roughness:1}),cliffMat=flat({color:0x6b756d,roughness:1});for(let i=0;i<18;i++){const t=.02+Math.random()*.16,s=i%2?1:-1;rockAt(t,s*(7+Math.random()*15),1.5+Math.random()*4,i%3?cliffMat:islandMat)}
const sun=new THREE.Mesh(new THREE.IcosahedronGeometry(5.8,2),new THREE.MeshBasicMaterial({color:0xffd59d,toneMapped:false}));sun.position.set(-22,13,-50);scene.add(sun);
const trunkMat=flat({color:0x2b2118,roughness:1}),leafDark=flat({color:0x123f2c,roughness:1}),leafLight=flat({color:0x245c3d,roughness:1}),moss=flat({color:0x466448,roughness:1});
for(let i=0;i<(lowPower?110:205);i++){const t=.202+Math.random()*.198,{p,side}=basisAt(t),s=i%2?1:-1,off=s*(2.4+Math.random()*11),h=3+Math.random()*6;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.11,.2,h,5),trunkMat);trunk.position.copy(p).addScaledVector(side,off);trunk.position.y+=h/2-.15;scene.add(trunk);const layers=2+(i%2);for(let k=0;k<layers;k++){const crown=new THREE.Mesh(new THREE.ConeGeometry(1.15+Math.random()*.7,2.3+Math.random()*1.6,6),k%2?leafDark:leafLight);crown.position.copy(trunk.position);crown.position.y+=h*.32+k*.9;scene.add(crown)}if(i%5===0)rockAt(t,s*(2.2+Math.random()*4),.35+Math.random()*.7,moss)}
const shaftMat=new THREE.MeshBasicMaterial({color:0xd9ffe4,transparent:true,opacity:.055,depthWrite:false,side:THREE.DoubleSide});for(let i=0;i<14;i++){const t=.21+i*.013,{p,side}=basisAt(t),beam=new THREE.Mesh(new THREE.CylinderGeometry(.08,1.1,10,6,1,true),shaftMat);beam.position.copy(p).addScaledVector(side,(i%2?1:-1)*(2+Math.random()*4));beam.position.y+=5;beam.rotation.z=(i%2?1:-1)*.18;scene.add(beam)}
const fireGeo=new THREE.BufferGeometry(),fire=[];for(let i=0;i<(lowPower?100:220);i++)fire.push((Math.random()-.5)*18,1+Math.random()*5,-52-Math.random()*30);fireGeo.setAttribute('position',new THREE.Float32BufferAttribute(fire,3));export const fireflies=new THREE.Points(fireGeo,new THREE.PointsMaterial({color:0xb9ffc7,size:.035,transparent:true,opacity:.55,depthWrite:false}));scene.add(fireflies);
const sandMat=flat({color:0xcf8c4e,roughness:1}),mesa=flat({color:0x9e5030,roughness:1}),mesa2=flat({color:0xb96435,roughness:1}),cactus=flat({color:0x466848,roughness:1});
for(let i=0;i<(lowPower?52:92);i++){const t=.405+Math.random()*.19,s=i%2?1:-1,off=s*(4+Math.random()*14);rockAt(t,off,1.2+Math.random()*3.5,i%3?mesa:mesa2)}
for(let i=0;i<16;i++){const t=.41+i*.011,{p,side}=basisAt(t),dune=new THREE.Mesh(new THREE.IcosahedronGeometry(2.8+Math.random()*2.6,1),sandMat);dune.scale.y=.18;dune.position.copy(p).addScaledVector(side,(i%2?1:-1)*(6+Math.random()*10));dune.position.y-=.5;scene.add(dune)}
for(let i=0;i<18;i++){const t=.41+Math.random()*.18,{p,side}=basisAt(t),s=i%2?1:-1,c=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,1.6+Math.random()*1.6,6),cactus);c.position.copy(p).addScaledVector(side,s*(3.4+Math.random()*8));c.position.y+=.8;scene.add(c)}
const archMat=flat({color:0xa85432,roughness:1});for(const t of [.47,.555]){const {p,tangent,side}=basisAt(t);const arch=new THREE.Mesh(new THREE.TorusGeometry(3.2,.58,6,12,Math.PI),archMat);arch.position.copy(p).addScaledVector(side,t===.47?8:-8);arch.position.y+=2.3;arch.rotation.y=Math.atan2(tangent.x,-tangent.z);arch.rotation.z=Math.PI;scene.add(arch)}
const dustGeo=new THREE.BufferGeometry(),dustPos=[];for(let i=0;i<(lowPower?320:760);i++)dustPos.push((Math.random()-.5)*28,(Math.random()-.5)*4,-82-Math.random()*55);dustGeo.setAttribute('position',new THREE.Float32BufferAttribute(dustPos,3));export const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xffc176,size:.04,transparent:true,opacity:.34,depthWrite:false}));scene.add(dust);
const tower=flat({color:0x08111c,roughness:.32,metalness:.6,emissive:0x02070d,emissiveIntensity:.6}),cyan=flat({color:0x0b1721,roughness:.22,metalness:.7,emissive:0x51e7ff,emissiveIntensity:4.2}),magenta=flat({color:0x17101d,roughness:.22,metalness:.7,emissive:0xff4ccf,emissiveIntensity:3.5}),amber=flat({color:0x18140d,roughness:.25,metalness:.5,emissive:0xffae4a,emissiveIntensity:3});
for(let i=0;i<(lowPower?95:170);i++){const t=.603+Math.random()*.195,s=i%2?1:-1,off=s*(4.3+Math.random()*10),h=3+Math.random()*12;boxAt(t,off,.7+Math.random()*1.5,h,.8+Math.random()*1.8,i%13===0?magenta:i%9===0?cyan:i%17===0?amber:tower)}
for(let i=0;i<12;i++){const t=.615+i*.014,{p,tangent}=basisAt(t),gantry=new THREE.Group();const barMat=i%3===0?cyan:flat({color:0x1c2631,roughness:.6});const top=new THREE.Mesh(new THREE.BoxGeometry(6.6,.12,.12),barMat);top.position.y=2.8;gantry.add(top);[-1,1].forEach(s=>{const post=new THREE.Mesh(new THREE.BoxGeometry(.1,2.8,.1),barMat);post.position.set(s*3.1,1.4,0);gantry.add(post)});gantry.position.copy(p);gantry.quaternion.setFromUnitVectors(FORWARD,tangent);scene.add(gantry)}
const rainGeo=new THREE.BufferGeometry(),rainPos=[];for(let i=0;i<(lowPower?850:1900);i++)rainPos.push((Math.random()-.5)*20,Math.random()*12,-132-Math.random()*48);rainGeo.setAttribute('position',new THREE.Float32BufferAttribute(rainPos,3));export const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0xc7f4ff,size:.025,transparent:true,opacity:.42,depthWrite:false}));scene.add(rain);
const snow=flat({color:0xdfeaf1,roughness:.94}),rock=flat({color:0x28384a,roughness:.94}),pine=flat({color:0x0b281f,roughness:1}),crystal=flat({color:0xa8f5ff,roughness:.28,metalness:.18,emissive:0x2a91aa,emissiveIntensity:1.1});
for(let i=0;i<(lowPower?75:140);i++){const t=.802+Math.random()*.195,s=i%2?1:-1,off=s*(3+Math.random()*11);if(i%4===0)rockAt(t,off,.8+Math.random()*2.2,i%2?snow:rock);else{const {p,side}=basisAt(t),tree=new THREE.Mesh(new THREE.ConeGeometry(.55+Math.random()*.55,2+Math.random()*3.5,6),pine);tree.position.copy(p).addScaledVector(side,off);tree.position.y+=1;scene.add(tree)}}
for(let i=0;i<30;i++){const t=.81+Math.random()*.18,s=i%2?1:-1,{p,side}=basisAt(t),c=new THREE.Mesh(new THREE.OctahedronGeometry(.24+Math.random()*.55,0),crystal);c.scale.y=1.8+Math.random()*2.4;c.position.copy(p).addScaledVector(side,s*(2.8+Math.random()*6));c.position.y+=.6;scene.add(c)}
for(let i=0;i<12;i++){const t=.815+i*.014,{p,side}=basisAt(t),m=new THREE.Mesh(new THREE.ConeGeometry(4+Math.random()*4,7+Math.random()*7,5),i%2?snow:rock);m.position.copy(p).addScaledVector(side,(i%2?1:-1)*(10+Math.random()*12));m.position.y+=2.4;scene.add(m)}
const starGeo=new THREE.BufferGeometry(),starPos=[];for(let i=0;i<(lowPower?420:1100);i++)starPos.push((Math.random()-.5)*90,8+Math.random()*30,-160-Math.random()*85);starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPos,3));export const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xd9f6ff,size:.04,transparent:true,opacity:.84,depthWrite:false}));scene.add(stars);
const auroraMat=new THREE.MeshBasicMaterial({color:0x67ffc5,transparent:true,opacity:.085,side:THREE.DoubleSide,depthWrite:false});export const auroras=[];for(let i=0;i<5;i++){const r=new THREE.Mesh(new THREE.PlaneGeometry(20,5,20,1),auroraMat.clone());r.position.set((i-2)*7,16+i*1.3,-186-i*6);r.rotation.x=-.18;r.rotation.z=(i-2)*.07;scene.add(r);auroras.push(r)}
const snowGeo=new THREE.BufferGeometry(),snowPos=[];for(let i=0;i<(lowPower?450:1000);i++)snowPos.push((Math.random()-.5)*22,Math.random()*12,-165-Math.random()*55);snowGeo.setAttribute('position',new THREE.Float32BufferAttribute(snowPos,3));export const snowfall=new THREE.Points(snowGeo,new THREE.PointsMaterial({color:0xffffff,size:.028,transparent:true,opacity:.52,depthWrite:false}));scene.add(snowfall);
