import {THREE,scene,camera,renderer,composer,bloom,rim,curve,basisAt,WORLD,UP,FORWARD,clamp,damp,coarse,reduceMotion,lowPower,loaderEl,loadBar,loadStatus,chapters,worldIndex,worldName,worldMeta,resize} from './core.js';
import {water,dust,rain,stars} from './worlds.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';

const carRig=new THREE.Group();scene.add(carRig);let car=null,wheels=[];
const bodyMat=new THREE.MeshPhysicalMaterial({color:0x9da7b0,metalness:1,roughness:.19,clearcoat:1,clearcoatRoughness:.035,envMapIntensity:1.8}),detailsMat=new THREE.MeshStandardMaterial({color:0x0b0c0e,metalness:1,roughness:.24,envMapIntensity:1.5}),glassMat=new THREE.MeshPhysicalMaterial({color:0x8eb5c7,metalness:.12,roughness:.05,transmission:.72,transparent:true,opacity:.82,envMapIntensity:1.3});
function fallbackCar(){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1.65,.38,3.6),bodyMat);b.position.y=.42;g.add(b);return g}car=fallbackCar();carRig.add(car);
const draco=new DRACOLoader();draco.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');const gltfLoader=new GLTFLoader();gltfLoader.setDRACOLoader(draco);loadStatus.textContent='Loading the car';
gltfLoader.load('https://threejs.org/examples/models/gltf/ferrari.glb',gltf=>{const root=gltf.scene.children[0]||gltf.scene;root.scale.setScalar(1.15);root.rotation.y=Math.PI;const body=root.getObjectByName('body');if(body)body.material=bodyMat;['rim_fl','rim_fr','rim_rr','rim_rl','trim'].forEach(n=>{const o=root.getObjectByName(n);if(o)o.material=detailsMat});const glass=root.getObjectByName('glass');if(glass)glass.material=glassMat;wheels=['wheel_fl','wheel_fr','wheel_rl','wheel_rr'].map(n=>root.getObjectByName(n)).filter(Boolean);root.traverse(o=>{if(o.isMesh){o.castShadow=!lowPower;o.receiveShadow=true}});const box=new THREE.Box3().setFromObject(root),ctr=box.getCenter(new THREE.Vector3());root.position.x-=ctr.x;root.position.z-=ctr.z;root.position.y-=box.min.y;carRig.remove(car);car=root;carRig.add(root);loadBar.style.width='100%';loadStatus.textContent='Ready';setTimeout(()=>loaderEl.classList.add('done'),350)},xhr=>{if(xhr.total)loadBar.style.width=(15+xhr.loaded/xhr.total*80)+'%'},()=>{loadBar.style.width='100%';loadStatus.textContent='Fallback car';setTimeout(()=>loaderEl.classList.add('done'),400)});setTimeout(()=>{if(!loaderEl.classList.contains('done'))loaderEl.classList.add('done')},8000);
const shadowTex=(()=>{const c=document.createElement('canvas');c.width=256;c.height=128;const q=c.getContext('2d'),g=q.createRadialGradient(128,64,2,128,64,95);g.addColorStop(0,'rgba(0,0,0,.72)');g.addColorStop(1,'rgba(0,0,0,0)');q.fillStyle=g;q.fillRect(0,0,256,128);return new THREE.CanvasTexture(c)})();const carShadow=new THREE.Mesh(new THREE.PlaneGeometry(2.7,1.2),new THREE.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false,toneMapped:false}));carShadow.rotation.x=-Math.PI/2;carShadow.position.y=.015;carRig.add(carShadow);
const trailMat=new THREE.MeshBasicMaterial({color:0xc5f5ff,transparent:true,opacity:0,depthWrite:false,toneMapped:false,blending:THREE.AdditiveBlending}),trailL=new THREE.Mesh(new THREE.PlaneGeometry(.05,4),trailMat),trailR=trailL.clone();trailL.rotation.x=trailR.rotation.x=-Math.PI/2;trailL.position.set(-.68,.03,2.3);trailR.position.set(.68,.03,2.3);carRig.add(trailL,trailR);
const sprayGeo=new THREE.BufferGeometry(),sprayPos=[];for(let i=0;i<(lowPower?70:150);i++)sprayPos.push((Math.random()-.5)*1.6,.08+Math.random()*.45,1+Math.random()*2.8);sprayGeo.setAttribute('position',new THREE.Float32BufferAttribute(sprayPos,3));const sprayMat=new THREE.PointsMaterial({color:0xcdefff,size:.025,transparent:true,opacity:0,depthWrite:false}),spray=new THREE.Points(sprayGeo,sprayMat);carRig.add(spray);
const streakGeo=new THREE.BufferGeometry(),streakPos=[];for(let i=0;i<(lowPower?70:170);i++)streakPos.push((Math.random()-.5)*12,(Math.random()-.5)*6,-2-Math.random()*20);streakGeo.setAttribute('position',new THREE.Float32BufferAttribute(streakPos,3));const streakMat=new THREE.PointsMaterial({color:0xe7fbff,size:.022,transparent:true,opacity:0,depthWrite:false}),streaks=new THREE.Points(streakGeo,streakMat);camera.add(streaks);scene.add(camera);

let target=.012,progress=.012,lastY=scrollY,velocity=0,camPos=new THREE.Vector3(),camQuat=new THREE.Quaternion(),firstCamera=true;function onScroll(){const total=Math.max(document.documentElement.scrollHeight-innerHeight,1);target=.012+(scrollY/total)*.976;const dy=Math.abs(scrollY-lastY);lastY=scrollY;velocity=Math.min(1,velocity+dy/650)}addEventListener('scroll',onScroll,{passive:true});onScroll();
function syncHud(){const total=Math.max(document.documentElement.scrollHeight-innerHeight,1),p=scrollY/total,idx=clamp(Math.floor(p*chapters.length),0,chapters.length-1),ch=chapters[idx];worldIndex.textContent=String(idx+1).padStart(2,'0');worldName.textContent=ch.dataset.name;worldMeta.textContent=ch.dataset.meta;document.documentElement.style.setProperty('--progress',(p*100)+'%')}
const lookMatrix=new THREE.Matrix4(),desiredQuat=new THREE.Quaternion(),clock=new THREE.Clock();
function render(){const dt=Math.min(clock.getDelta(),.04),time=clock.elapsedTime;progress=damp(progress,target,reduceMotion?16:3.4,dt);velocity=damp(velocity,0,3.2,dt);syncHud();const {p,tangent,side,normal}=basisAt(progress),next=basisAt(clamp(progress+.007,0,1)),turn=clamp(side.dot(next.side),-.99,1),bank=clamp((1-turn)*4.5,0,.11);carRig.position.copy(p).addScaledVector(normal,.025);desiredQuat.setFromUnitVectors(FORWARD,tangent);desiredQuat.multiply(new THREE.Quaternion().setFromAxisAngle(tangent,bank));carRig.quaternion.slerp(desiredQuat,1-Math.exp(-dt*9));
 const carSpeed=.7+velocity*3.6;wheels.forEach(w=>w.rotation.x-=dt*carSpeed*7.5);trailMat.opacity=.02+velocity*.26;trailL.scale.y=trailR.scale.y=1+velocity*1.7;sprayMat.opacity=(progress<.2||progress>.6&&progress<.8)?.08+velocity*.34:progress>.4&&progress<.6?.04+velocity*.22:.02;spray.position.z=(time*5)%1;streakMat.opacity=velocity*.18;
 const desiredPos=p.clone().addScaledVector(tangent,coarse?-6.1:-7.1).addScaledVector(normal,coarse?2.15:2.55).addScaledVector(side,Math.sin(progress*Math.PI*4)*.13);if(firstCamera)camPos.copy(desiredPos);else camPos.lerp(desiredPos,1-Math.exp(-dt*3.6));camera.position.copy(camPos);const focus=curve.getPointAt(clamp(progress+.055+velocity*.008,0,1)).addScaledVector(UP,.68);lookMatrix.lookAt(camera.position,focus,UP);desiredQuat.setFromRotationMatrix(lookMatrix);if(firstCamera){camQuat.copy(desiredQuat);firstCamera=false}else camQuat.slerp(desiredQuat,1-Math.exp(-dt*4.1));camera.quaternion.copy(camQuat);camera.fov=damp(camera.fov,39+velocity*3.2,3.5,dt);camera.updateProjectionMatrix();rim.position.copy(p).addScaledVector(side,-1.8).addScaledVector(normal,1.2).addScaledVector(tangent,-.5);
 const wi=clamp(Math.floor(progress*5),0,4),w=WORLD[wi];scene.fog.color.lerp(new THREE.Color(w.fog),1-Math.exp(-dt*2.2));scene.background.lerp(new THREE.Color(w.bg),1-Math.exp(-dt*1.8));scene.fog.density=damp(scene.fog.density,wi===1?.03:wi===3?.018:wi===4?.013:.009,2.4,dt);renderer.toneMappingExposure=damp(renderer.toneMappingExposure,wi===2?1.22:wi===3?.95:1.08,2.2,dt);bloom.strength=damp(bloom.strength,(lowPower?.18:.3)+(wi===3?.22:0)+velocity*.16,3,dt);water.material.color.offsetHSL(0,0,Math.sin(time*.3)*.0004);dust.rotation.y=time*.015;rain.position.y=-((time*7)%4);stars.rotation.y=time*.003;document.documentElement.style.setProperty('--speed',velocity.toFixed(3));composer.render();requestAnimationFrame(render)}render();addEventListener('resize',resize);
