import {THREE,scene,lowPower,basisAt,boxAt,rockAt} from './core.js';
export const waterMat=new THREE.MeshPhysicalMaterial({color:0x1b6680,roughness:.12,metalness:.2,transparent:true,opacity:.86,clearcoat:1});export const water=new THREE.Mesh(new THREE.PlaneGeometry(180,90),waterMat);water.rotation.x=-Math.PI/2;water.position.set(0,-1.05,-18);scene.add(water);
const pylonMat=new THREE.MeshStandardMaterial({color:0xc3c8c8,roughness:.8});for(let t=.015;t<.195;t+=.018){const {p,side}=basisAt(t);[-1,1].forEach(s=>{const py=new THREE.Mesh(new THREE.CylinderGeometry(.13,.16,2.3,8),pylonMat);py.position.copy(p).addScaledVector(side,s*2.1);py.position.y-=1.1;scene.add(py)})}
const railMat=new THREE.MeshStandardMaterial({color:0xeaf1f1,metalness:.35,roughness:.35});for(let t=.01;t<.2;t+=.015){[-1,1].forEach(s=>{const {p,tangent,side,normal}=basisAt(t),r=new THREE.Mesh(new THREE.BoxGeometry(.06,.32,2.2),railMat);r.position.copy(p).addScaledVector(side,s*2.55).addScaledVector(normal,.25);r.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),tangent);scene.add(r)})}
const oceanSun=new THREE.Mesh(new THREE.SphereGeometry(7,32,16),new THREE.MeshBasicMaterial({color:0xffd7a0,toneMapped:false}));oceanSun.position.set(-18,13,-45);scene.add(oceanSun);

const trunkMat=new THREE.MeshStandardMaterial({color:0x251a12,roughness:1}),leafMat=new THREE.MeshStandardMaterial({color:0x143d2a,roughness:.92}),mossMat=new THREE.MeshStandardMaterial({color:0x38543a,roughness:1});
for(let i=0;i<(lowPower?75:135);i++){const t=.205+Math.random()*.19,{p,side}=basisAt(t),s=i%2?1:-1,off=s*(3+Math.random()*7),h=3+Math.random()*5;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.13,.22,h,6),trunkMat);trunk.position.copy(p).addScaledVector(side,off);trunk.position.y+=h/2-.2;trunk.rotation.z=(Math.random()-.5)*.08;scene.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1+Math.random()*.7,2.6+Math.random()*2,7),leafMat);crown.position.copy(trunk.position);crown.position.y+=h*.45+1.2;scene.add(crown);if(i%4===0)rockAt(t,s*(2.7+Math.random()*2),.35+Math.random()*.5,mossMat)}
const shaftMat=new THREE.MeshBasicMaterial({color:0xd6f7d8,transparent:true,opacity:.045,depthWrite:false,side:THREE.DoubleSide});for(let i=0;i<10;i++){const t=.22+i*.016,{p,side}=basisAt(t),beam=new THREE.Mesh(new THREE.CylinderGeometry(.15,1.2,9,10,1,true),shaftMat);beam.position.copy(p).addScaledVector(side,(i%2?1:-1)*(2+Math.random()*4));beam.position.y+=4.5;beam.rotation.z=(i%2?1:-1)*.2;scene.add(beam)}

const sandMat=new THREE.MeshStandardMaterial({color:0xc98949,roughness:1}),mesaMat=new THREE.MeshStandardMaterial({color:0x9b4e2c,roughness:.96});for(let i=0;i<(lowPower?38:70);i++){const t=.405+Math.random()*.19,s=i%2?1:-1,off=s*(4+Math.random()*10);rockAt(t,off,1+Math.random()*2.5,i%3?mesaMat:sandMat)}
for(let i=0;i<12;i++){const t=.42+i*.014,{p,side}=basisAt(t),dune=new THREE.Mesh(new THREE.SphereGeometry(3+Math.random()*2,12,8),sandMat);dune.scale.y=.18;dune.position.copy(p).addScaledVector(side,(i%2?1:-1)*(5+Math.random()*8));dune.position.y-=.7;scene.add(dune)}
const dustGeo=new THREE.BufferGeometry(),dustPos=[];for(let i=0;i<(lowPower?250:600);i++)dustPos.push((Math.random()-.5)*22,(Math.random()-.5)*3,-75-Math.random()*50);dustGeo.setAttribute('position',new THREE.Float32BufferAttribute(dustPos,3));export const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xffc77c,size:.035,transparent:true,opacity:.3,depthWrite:false}));scene.add(dust);

const towerMat=new THREE.MeshStandardMaterial({color:0x08111b,roughness:.3,metalness:.7,emissive:0x03080d,emissiveIntensity:.8}),cyan=new THREE.MeshStandardMaterial({color:0x0d1720,roughness:.25,metalness:.8,emissive:0x45dcff,emissiveIntensity:3.8}),violet=new THREE.MeshStandardMaterial({color:0x130f1c,roughness:.25,metalness:.8,emissive:0x9c60ff,emissiveIntensity:3});
for(let i=0;i<92;i++){const t=.605+Math.random()*.19,s=i%2?1:-1,off=s*(3.8+Math.random()*7),h=3+Math.random()*9;boxAt(t,off,.7+Math.random()*1.2,h,.9+Math.random()*1.5,i%8===0?(i%2?cyan:violet):towerMat)}
const rainGeo=new THREE.BufferGeometry(),rainPos=[];for(let i=0;i<(lowPower?650:1600);i++)rainPos.push((Math.random()-.5)*18,Math.random()*10,-118-Math.random()*48);rainGeo.setAttribute('position',new THREE.Float32BufferAttribute(rainPos,3));export const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0xc8f4ff,size:.022,transparent:true,opacity:.4,depthWrite:false}));scene.add(rain);

const snowMat=new THREE.MeshStandardMaterial({color:0xdfeaf0,roughness:.85}),rockDark=new THREE.MeshStandardMaterial({color:0x1b2430,roughness:.9}),pineMat=new THREE.MeshStandardMaterial({color:0x0a201b,roughness:1});for(let i=0;i<(lowPower?55:100);i++){const t=.805+Math.random()*.19,s=i%2?1:-1,off=s*(3.4+Math.random()*8);if(i%3===0)rockAt(t,off,.7+Math.random()*1.8,i%2?snowMat:rockDark);else{const {p,side}=basisAt(t),tree=new THREE.Mesh(new THREE.ConeGeometry(.6+Math.random()*.5,2+Math.random()*3,7),pineMat);tree.position.copy(p).addScaledVector(side,off);tree.position.y+=1;scene.add(tree)}}
const starGeo=new THREE.BufferGeometry(),starPos=[];for(let i=0;i<(lowPower?350:900);i++)starPos.push((Math.random()-.5)*80,8+Math.random()*28,-145-Math.random()*80);starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPos,3));export const stars=new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xd9f5ff,size:.035,transparent:true,opacity:.8,depthWrite:false}));scene.add(stars);
const auroraMat=new THREE.MeshBasicMaterial({color:0x65ffc7,transparent:true,opacity:.08,side:THREE.DoubleSide,depthWrite:false});for(let i=0;i<4;i++){const ribbon=new THREE.Mesh(new THREE.PlaneGeometry(18,5,20,1),auroraMat.clone());ribbon.position.set((i-1.5)*7,14+i*1.5,-170-i*6);ribbon.rotation.x=-.15;ribbon.rotation.z=(i-1.5)*.08;scene.add(ribbon)}
